export interface MdMsBranchData {
  title: string;
  metaTitle: string;
  metaDescription: string;
  bannerTitle: string;
  bannerDescription: string;
  bannerImage: string;
  overviewTitle: string;
  overviewContent: string;
  highlights: string[];
  previewTitle: string;
  previewPoints: string[];
}

export const mdmsBranchesData: Record<string, MdMsBranchData> = {
  "general-medicine": {
    title: "MD General Medicine",
    metaTitle: "MD General Medicine | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MD General Medicine — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MD General Medicine",
    bannerDescription: "The foundation branch of internal medicine offering the widest clinical exposure and a gateway to DM super-specialty training.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD General Medicine",
    overviewContent:
      "General Medicine is the foundation branch of internal medicine, dealing with the prevention, diagnosis, and non-surgical management of adult diseases. It offers the widest clinical exposure across all medical specialties and is the gateway to super-specialties such as Cardiology, Neurology, Nephrology, and Endocrinology.",
    highlights: [
      "Widest clinical exposure across all medical branches",
      "Strong demand in hospitals, private practice, and academia",
      "Gateway to DM super-specialty training",
      "Career options in critical care, emergency, and internal medicine",
    ],
    previewTitle: "Why Choose General Medicine",
    previewPoints: [
      "Covers the full spectrum of adult medical care",
      "Excellent postgraduate and super-specialty prospects",
      "Strong physician demand in India and abroad",
      "High-value patient base across public and private hospitals",
    ],
  },
  pediatrics: {
    title: "MD Pediatrics",
    metaTitle: "MD Pediatrics | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MD Pediatrics — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MD Pediatrics",
    bannerDescription: "Focused on the medical care of infants, children, and adolescents, combining clinical care with preventive child health.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD Pediatrics",
    overviewContent:
      "Pediatrics focuses on the medical care of infants, children, and adolescents, including growth, development, and childhood diseases. It combines clinical care with preventive medicine, immunization, and national child health programs.",
    highlights: [
      "High demand in hospitals, clinics, and child health programs",
      "Rewarding career with strong community impact",
      "Scope in neonatology and pediatric super-specialties",
      "Excellent opportunities for private practice",
    ],
    previewTitle: "Why Choose Pediatrics",
    previewPoints: [
      "Work with children and families across all communities",
      "Strong demand for pediatricians in India and abroad",
      "Pathway to neonatology and pediatric super-specialties",
      "Fulfilling and respected career choice",
    ],
  },
  dermatology: {
    title: "MD Dermatology, Venereology & Leprosy",
    metaTitle: "MD Dermatology | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MD Dermatology — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MD Dermatology",
    bannerDescription: "A highly sought-after clinical branch covering skin, hair, nail, and aesthetic treatments with strong private practice potential.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD Dermatology, Venereology & Leprosy",
    overviewContent:
      "Dermatology covers the diagnosis and treatment of skin, hair, nail, and mucous membrane disorders, along with sexually transmitted diseases and leprosy. It is one of the most preferred PG branches due to its clinical diversity and exceptional private practice potential, including aesthetic and cosmetic dermatology.",
    highlights: [
      "One of the most sought-after PG branches",
      "Excellent earning potential in private practice",
      "Growing demand for cosmetic and aesthetic treatments",
      "Balanced lifestyle with low emergency burden",
    ],
    previewTitle: "Why Choose Dermatology",
    previewPoints: [
      "High demand for skin, hair, and aesthetic treatments",
      "Excellent private practice and earning potential",
      "Growing scope of cosmetic and laser dermatology",
      "Comparatively predictable working hours",
    ],
  },
  radiology: {
    title: "MD Radiodiagnosis",
    metaTitle: "MD Radiology | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MD Radiodiagnosis — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MD Radiodiagnosis",
    bannerDescription: "A technology-driven branch offering excellent career prospects in diagnostic imaging, teleradiology, and interventional radiology.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD Radiodiagnosis",
    overviewContent:
      "Radiodiagnosis is a technology-driven specialty involving X-rays, CT, MRI, ultrasound, and interventional radiology. It is central to modern diagnostics with strong career prospects in hospitals, diagnostic chains, and teleradiology.",
    highlights: [
      "Excellent demand in hospitals and diagnostic centers",
      "Growing teleradiology and remote reporting opportunities",
      "High earning potential with manageable workload",
      "Increasing scope of interventional radiology",
    ],
    previewTitle: "Why Choose Radiodiagnosis",
    previewPoints: [
      "Technology-driven specialty with modern diagnostic tools",
      "Strong demand in India and international markets",
      "Flexible career options including teleradiology",
      "Rapidly growing interventional radiology scope",
    ],
  },
  anaesthesiology: {
    title: "MD Anaesthesiology",
    metaTitle: "MD Anaesthesiology | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MD Anaesthesiology — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MD Anaesthesiology",
    bannerDescription: "A procedure-driven specialty with critical care and pain management scope, offering excellent career opportunities.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD Anaesthesiology",
    overviewContent:
      "Anaesthesiology deals with anesthesia, perioperative care, critical care, pain management, and resuscitation. It is a procedure-driven specialty essential to every surgical setup, with growing scope in ICU and pain medicine.",
    highlights: [
      "High demand in every hospital and surgical setup",
      "Strong scope in critical care and pain management",
      "Attractive stipend and career growth",
      "Pathway to DM critical care and pain medicine",
    ],
    previewTitle: "Why Choose Anaesthesiology",
    previewPoints: [
      "Essential role in every surgical and emergency setup",
      "Growing demand for intensivists and pain specialists",
      "Excellent private practice and corporate hospital opportunities",
      "Rewarding and procedure-driven career",
    ],
  },
  psychiatry: {
    title: "MD Psychiatry",
    metaTitle: "MD Psychiatry | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MD Psychiatry — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MD Psychiatry",
    bannerDescription: "A growing branch addressing mental health with strong clinical, academic, and community-care opportunities.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD Psychiatry",
    overviewContent:
      "Psychiatry deals with the diagnosis, treatment, and prevention of mental, emotional, and behavioral disorders. With rising mental health awareness, it offers strong clinical, academic, and community-care opportunities.",
    highlights: [
      "Rapidly growing demand for mental health professionals",
      "Fulfilling clinical and community-care role",
      "Balanced lifestyle and predictable working hours",
      "Opportunities in de-addiction and telepsychiatry",
    ],
    previewTitle: "Why Choose Psychiatry",
    previewPoints: [
      "Growing awareness and demand for mental health care",
      "Rewarding career with meaningful social impact",
      "Low physical emergency burden",
      "Scope in de-addiction, telepsychiatry, and research",
    ],
  },
  pathology: {
    title: "MD Pathology",
    metaTitle: "MD Pathology | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MD Pathology — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MD Pathology",
    bannerDescription: "A diagnostic science branch with strong laboratory, research, and academic career opportunities.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD Pathology",
    overviewContent:
      "Pathology is the diagnostic science behind disease diagnosis, including histopathology, hematology, clinical pathology, and laboratory medicine. It offers strong opportunities in diagnostic laboratories, hospitals, academia, and research.",
    highlights: [
      "Strong demand in diagnostic laboratories and hospitals",
      "Excellent academic and research opportunities",
      "Supportive of balanced lifestyle",
      "Scope in molecular pathology and forensics",
    ],
    previewTitle: "Why Choose Pathology",
    previewPoints: [
      "Central to every disease diagnosis",
      "Growing demand in private diagnostic chains",
      "Strong research and teaching career path",
      "Predictable working hours with minimal emergency duty",
    ],
  },
  "general-surgery": {
    title: "MS General Surgery",
    metaTitle: "MS General Surgery | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MS General Surgery — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MS General Surgery",
    bannerDescription: "A surgical foundation branch offering broad operative exposure and a gateway to surgical super-specialties.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MS General Surgery",
    overviewContent:
      "General Surgery provides comprehensive training in surgical diagnosis, operative techniques, and perioperative care. It is the gateway to surgical super-specialties such as Gastro Surgery, Urology, Paediatric Surgery, and Surgical Oncology.",
    highlights: [
      "Broad operative exposure across all surgical fields",
      "Gateway to surgical super-specialty training",
      "Strong demand for skilled surgeons in India and abroad",
      "High-value, procedure-driven career",
    ],
    previewTitle: "Why Choose General Surgery",
    previewPoints: [
      "Comprehensive surgical training across specialties",
      "Excellent pathway to MCh super-specialties",
      "Strong professional demand and respect",
      "High earning potential in private practice",
    ],
  },
  orthopaedics: {
    title: "MS Orthopaedics",
    metaTitle: "MS Orthopaedics | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MS Orthopaedics — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MS Orthopaedics",
    bannerDescription: "A procedure-rich branch dealing with bones, joints, trauma, and sports injuries with excellent career prospects.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MS Orthopaedics",
    overviewContent:
      "Orthopaedics deals with the diagnosis and surgical treatment of musculoskeletal conditions, trauma, fractures, joint replacements, and sports injuries. It is one of the most sought-after surgical branches with excellent clinical and earning potential.",
    highlights: [
      "High demand for trauma and joint replacement surgery",
      "Excellent private practice opportunities",
      "Growing scope of sports medicine and arthroscopy",
      "Procedure-rich and technically advanced branch",
    ],
    previewTitle: "Why Choose Orthopaedics",
    previewPoints: [
      "High-volume trauma and emergency demand",
      "Growing joint replacement and arthroscopy scope",
      "Excellent earning potential in private practice",
      "Advanced surgical technology and techniques",
    ],
  },
  "obstetrics-gynaecology": {
    title: "MS Obstetrics & Gynaecology",
    metaTitle: "MS Obstetrics & Gynaecology | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MS Obstetrics & Gynaecology — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MS Obstetrics & Gynaecology",
    bannerDescription: "A high-demand branch covering women's health, childbirth, and gynecological surgery with strong career prospects.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MS Obstetrics & Gynaecology",
    overviewContent:
      "Obstetrics & Gynaecology covers antenatal and postnatal care, childbirth, and the surgical management of gynecological conditions. It is a high-demand branch with strong opportunities in hospitals, nursing homes, and private practice.",
    highlights: [
      "High and consistent demand in every community",
      "Excellent private practice and institutional career options",
      "Rewarding role in women's health and childbirth",
      "Scope in high-risk obstetrics and fertility medicine",
    ],
    previewTitle: "Why Choose Obstetrics & Gynaecology",
    previewPoints: [
      "Consistent clinical demand across India",
      "Strong private practice and hospital careers",
      "Fulfilling and respected specialty",
      "Growing scope in fertility and minimal-access surgery",
    ],
  },
  ent: {
    title: "MS Otorhinolaryngology (ENT)",
    metaTitle: "MS ENT | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MS Otorhinolaryngology (ENT) — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MS Otorhinolaryngology (ENT)",
    bannerDescription: "A versatile surgical branch covering ear, nose, throat, and head-neck disorders with strong clinical demand.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MS Otorhinolaryngology (ENT)",
    overviewContent:
      "ENT deals with disorders of the ear, nose, throat, and head-neck region, including surgery, endoscopy, and skull-base procedures. It offers a balanced mix of medical and surgical practice with strong demand.",
    highlights: [
      "High demand for ENT services in every region",
      "Balanced mix of medical and surgical practice",
      "Growing scope in cochlear implants and endoscopic surgery",
      "Excellent private practice opportunities",
    ],
    previewTitle: "Why Choose ENT",
    previewPoints: [
      "Consistent patient volume and clinical demand",
      "Mix of medical, surgical, and endoscopic practice",
      "Strong opportunities for private practice",
      "Growing head and neck oncology scope",
    ],
  },
  ophthalmology: {
    title: "MS Ophthalmology",
    metaTitle: "MS Ophthalmology | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to MS Ophthalmology — counselling, eligibility, career scope, and expert guidance for PG medical admissions.",
    bannerTitle: "MS Ophthalmology",
    bannerDescription: "A precision surgical branch covering eye care, cataract, refractive, and retinal surgery with excellent career prospects.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MS Ophthalmology",
    overviewContent:
      "Ophthalmology covers the medical and surgical care of the eye, including cataract, refractive, glaucoma, and retinal surgery. It is a precision-driven branch with excellent earning potential and high patient volume.",
    highlights: [
      "High patient volume with consistent demand",
      "Excellent private practice and surgery center opportunities",
      "Rapid advances in cataract and refractive surgery",
      "Strong academic and research scope",
    ],
    previewTitle: "Why Choose Ophthalmology",
    previewPoints: [
      "High-volume, high-precision surgical practice",
      "Excellent earning potential in private practice",
      "Growing scope in refractive and retinal surgery",
      "Rewarding impact on vision care",
    ],
  },
  "tamil-nadu": {
    title: "MD/MS in Tamil Nadu",
    metaTitle: "MD/MS in Tamil Nadu | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Secure MD/MS admission in top medical colleges across Tamil Nadu. Expert NEET PG counselling for government and private medical seats.",
    bannerTitle: "MD/MS Admissions in Tamil Nadu",
    bannerDescription: "Secure your PG medical seat in premier medical colleges across Tamil Nadu. Expert guidance for NEET PG counselling and admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Tamil Nadu",
    overviewContent:
      "Tamil Nadu is home to some of India's most reputed government and private medical colleges offering MD/MS seats through the Directorate of Medical Education (DME) counselling. With a strong clinical training environment, high patient inflow, and competitive NEET PG cutoffs, the state attracts postgraduate aspirants from across the country.",
    highlights: [
      "NEET PG counselling conducted by Tamil Nadu DME with transparent allotment rounds",
      "Renowned teaching hospitals with high clinical exposure and patient inflow",
      "Government college seats with affordable fee structures",
      "Strong demand for medical and surgical specialists in public and private healthcare",
    ],
    previewTitle: "Disclaimer Points",
    previewPoints: [
      "One mistake in document submission can lead to cancellation of admission, forfeiture of fees, and debarment from future counselling",
      "Not all candidates are eligible for Minority, Institutional, NRI, or special category seats. Eligibility needs to be verified before counselling",
      "Fee structures, bond conditions, and college-specific rules may differ across institutions",
    ],
  },
  kerala: {
    title: "MD/MS in Kerala",
    metaTitle: "MD/MS in Kerala | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Kerala MD/MS admissions — CAP counselling, eligibility, reservation, fees, and expert NEET PG guidance.",
    bannerTitle: "Kerala MD/MS Counselling Guide",
    bannerDescription: "Complete information on eligibility, CAP counselling, reservation, fee structure, and expert guidance for Kerala MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Kerala",
    overviewContent:
      "Kerala offers MD/MS seats through the Centralised Allotment Process (CAP) conducted by the Commissioner of Entrance Examinations. Known for its rich clinical exposure, strong academic culture, and a well-developed network of government and private medical colleges, Kerala is a popular destination for NEET PG aspirants.",
    highlights: [
      "Centralised Allotment Process (CAP) with online option submission",
      "Reservations across State Merit, EWS, SEBC, SC/ST, Management, NRI, Minority & AIQ",
      "Eligibility categories — Keralite, Non-Keralite Category I & II",
      "Strong teaching hospitals with high patient volume",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "Is your NEET PG rank alone enough to secure an MD/MS seat in Kerala?",
      "Do you know how Kerala's CAP counselling actually works?",
      "Are you aware of the hidden eligibility and counselling rules beyond your NEET PG rank?",
    ],
  },
  karnataka: {
    title: "MD/MS in Karnataka",
    metaTitle: "MD/MS in Karnataka | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Karnataka MD/MS counselling — instructions, fee structure, document requirements, and expert guidance.",
    bannerTitle: "Karnataka MD/MS Counselling Guide",
    bannerDescription: "Complete information on instructions, fee structure, and document requirements for Karnataka MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Karnataka",
    overviewContent:
      "Karnataka is one of the largest private medical education hubs in India, offering a vast number of MD/MS seats across government, private, and deemed universities. The state conducts NEET PG counselling through KEA with multiple rounds and a wide range of clinical branches.",
    highlights: [
      "Admissions based on NEET PG with counselling by KEA",
      "Large number of seats across private and deemed universities",
      "Separate fee structure for government and private colleges",
      "Wide availability of super-specialty clinical exposure",
    ],
    previewTitle: "Instructions for MD/MS Admission",
    previewPoints: [
      "Additional documents may be required depending on your category",
      "Mandatory affidavits and bonds before admission",
      "Document verification is more than just carrying originals",
    ],
  },
  pondicherry: {
    title: "MD/MS in Pondicherry",
    metaTitle: "MD/MS in Pondicherry | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Pondicherry MD/MS counselling — CENTAC process, eligibility, quotas, fee structure, and expert guidance.",
    bannerTitle: "Pondicherry MD/MS Counselling Guide",
    bannerDescription: "Complete information on CENTAC counselling, seat categories, eligibility, fee structure, and expert guidance for Pondicherry MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Pondicherry",
    overviewContent:
      "Pondicherry offers MD/MS seats through the Centralised Admission Committee (CENTAC) and through its reputed government and private medical institutions. With its union-territory status and central government medical college, Pondicherry provides attractive PG options at competitive fee structures.",
    highlights: [
      "CENTAC online counselling conducted in multiple rounds",
      "Seat categories — Government Quota, Management & NRI",
      "Reservation algorithm for Government Quota seats",
      "Refund and forfeiture rules for registration & tuition fees",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "Can students from other states also get MD/MS admission in Pondicherry, or is it only for Pondicherry domicile candidates?",
      "What is the difference between Government Quota, Management Quota, and NRI Quota in Pondicherry MD/MS admissions?",
      "Can I participate in both CENTAC counselling and MCC counselling for MD/MS, and which gives a better chance of a seat?",
    ],
  },
  telangana: {
    title: "MD/MS in Telangana",
    metaTitle: "MD/MS in Telangana | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Telangana MD/MS counselling — eligibility, reservation, application process, fees, and expert guidance.",
    bannerTitle: "Telangana MD/MS Counselling Guide",
    bannerDescription: "Complete information on eligibility, seat quota, reservation, application process, and fee structure for Telangana MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Telangana",
    overviewContent:
      "Telangana conducts MD/MS admissions under the Kaloji Narayana Rao University of Health Sciences (KNRUHS), offering seats in government, private, and minority institutions. With leading institutions like Osmania and Gandhi Medical Colleges, Telangana offers strong clinical training and competitive counselling.",
    highlights: [
      "Seats allotted under KNRUHS with online counselling",
      "Eligibility, reservation and admission rules clearly defined",
      "Online application and counselling process",
      "Fees and discontinuation rules for all seat categories",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "Do you know how Telangana prepares the final merit list and allots MD/MS seats?",
      "Are you aware of the reservation and category rules that apply to your profile?",
      "What is the difference between Competent Authority and Management Quota seats in Telangana?",
    ],
  },
  "andhra-pradesh": {
    title: "MD/MS in Andhra Pradesh",
    metaTitle: "MD/MS in Andhra Pradesh | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Andhra Pradesh MD/MS counselling — eligibility, categories, seat quotas, fees, and expert guidance.",
    bannerTitle: "Andhra Pradesh MD/MS Counselling Guide",
    bannerDescription: "Complete information on eligibility, Competent Authority and Management Quota seats, fee structure, and expert guidance for Andhra Pradesh MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Andhra Pradesh",
    overviewContent:
      "Andhra Pradesh conducts MD/MS counselling under the Director of Medical Education with a clear division of Competent Authority, Management Quota (Category-B), and NRI (Category-C) seats. The state's medical colleges offer strong clinical exposure and a well-structured counselling process.",
    highlights: [
      "Competent Authority, Management Quota (Category-B), and NRI (Category-C) seats",
      "Online counselling conducted by the state DME",
      "Transparent merit-based allotment with multiple rounds",
      "Strong network of government and private medical colleges",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "Can a single application make you eligible for every MD/MS seat category in Andhra Pradesh, or are separate counselling rules involved?",
      "What is the difference between Competent Authority, Management Quota (Category-B), and NRI (Category-C) seats — and which one are you actually eligible for?",
      "How do MD/MS tuition fees vary between seat categories, and which option is right for you?",
    ],
  },
  haryana: {
    title: "MD/MS in Haryana",
    metaTitle: "MD/MS in Haryana | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Haryana MD/MS counselling — eligibility, NRI category, fee structure, and expert NEET PG guidance.",
    bannerTitle: "Haryana MD/MS Counselling Guide",
    bannerDescription: "Complete information on seat distribution, eligibility criteria, NRI category, and counselling procedure for Haryana MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Haryana",
    overviewContent:
      "Haryana offers MD/MS seats through its state counselling body, including government, private, and NRI category seats. With proximity to Delhi and a growing number of medical colleges, Haryana is a favourable destination for NEET PG aspirants seeking quality training at competitive fees.",
    highlights: [
      "State counselling with government, private, and NRI seats",
      "Clear eligibility and reservation rules",
      "Well-defined fee structure across categories",
      "Growing clinical infrastructure and teaching hospitals",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "Admission to the NRI category requires careful verification of eligibility",
      "Can you claim a reserved category seat later if you forget to select your category during registration?",
      "Which category of seat gives you the highest chance of an MD/MS seat in Haryana based on your NEET PG score?",
    ],
  },
  punjab: {
    title: "MD/MS in Punjab",
    metaTitle: "MD/MS in Punjab | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Punjab MD/MS counselling — eligibility, seat categories, fee structure, and expert NEET PG guidance.",
    bannerTitle: "Punjab MD/MS Counselling Guide",
    bannerDescription: "Complete information on eligibility, seat categories, reservation, and counselling procedure for Punjab MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Punjab",
    overviewContent:
      "Punjab offers MD/MS seats through its state counselling authority with government, private, and NRI quota seats across reputed institutions. The state provides a balanced mix of clinical exposure, academic quality, and affordable private education options.",
    highlights: [
      "State counselling with government, private, and NRI seats",
      "Reputed government and private medical institutions",
      "Competitive fee structures across categories",
      "Strong clinical and hospital training environment",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "Do you know the difference between Government Quota, Management Quota, and NRI Quota seats in Punjab?",
      "Which reservation category are you actually eligible for in Punjab MD/MS counselling?",
      "What happens if a reserved or NRI seat remains vacant in later rounds of counselling?",
    ],
  },
  "himachal-pradesh": {
    title: "MD/MS in Himachal Pradesh",
    metaTitle: "MD/MS in Himachal Pradesh | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Himachal Pradesh MD/MS counselling — eligibility, seat categories, NRI quota, fees, and expert guidance.",
    bannerTitle: "Himachal Pradesh MD/MS Counselling Guide",
    bannerDescription: "Complete information on seat distribution, eligibility criteria, NRI category, and counselling procedure for Himachal Pradesh MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Himachal Pradesh",
    overviewContent:
      "Himachal Pradesh offers MD/MS seats in government and private medical colleges with a straightforward state counselling process. The state is known for its peaceful academic environment, affordable fee structures, and growing medical education infrastructure.",
    highlights: [
      "State counselling with government and private seats",
      "NRI category seats with clear eligibility rules",
      "Affordable fee structures in government institutions",
      "Growing number of PG seats year on year",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "Which category of seat gives you the highest chance of an MD/MS seat in Himachal Pradesh based on your NEET PG score?",
      "Can reserved category candidates apply under both their reserved category and the General category during counselling?",
      "What happens to NRI and reserved seats if they remain vacant in later rounds?",
    ],
  },
  "uttar-pradesh": {
    title: "MD/MS in Uttar Pradesh",
    metaTitle: "MD/MS in Uttar Pradesh | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Uttar Pradesh MD/MS counselling — eligibility, reservation, seat categories, fees, and expert guidance.",
    bannerTitle: "Uttar Pradesh MD/MS Counselling Guide",
    bannerDescription: "Complete information on eligibility, seat distribution, reservation, and counselling procedure for Uttar Pradesh MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Uttar Pradesh",
    overviewContent:
      "Uttar Pradesh offers one of the largest numbers of MD/MS seats in India through its state counselling conducted by the UP NEET PG cell. With premier institutions like KGMU and a vast network of government and private medical colleges, UP provides abundant PG opportunities across all clinical branches.",
    highlights: [
      "One of the largest pools of MD/MS seats in India",
      "State counselling with multiple rounds and choice filling",
      "Premier institutions including King George's Medical University",
      "Wide availability of clinical branches and specialities",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "Can reserved category candidates get admission through the General (Open Merit) category as well?",
      "How does the UP NEET PG choice filling and seat allotment process work across rounds?",
      "Which seat category gives you the best chance of securing your preferred branch in UP?",
    ],
  },
  bihar: {
    title: "MD/MS in Bihar",
    metaTitle: "MD/MS in Bihar | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Bihar MD/MS counselling — eligibility, seat categories, reservation, fees, and expert NEET PG guidance.",
    bannerTitle: "Bihar MD/MS Counselling Guide",
    bannerDescription: "Complete information on eligibility, seat distribution, reservation, and counselling procedure for Bihar MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Bihar",
    overviewContent:
      "Bihar offers MD/MS seats through its state counselling authority across government and private medical colleges. With improving healthcare infrastructure and growing PG capacity, Bihar presents attractive opportunities for NEET PG aspirants seeking quality training at competitive fees.",
    highlights: [
      "State counselling with government, private, and minority seats",
      "Improving PG infrastructure and teaching hospitals",
      "Competitive fee structures across categories",
      "Merit-based allotment with multiple counselling rounds",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "Do you know how Bihar prepares the final merit list and allots MD/MS seats based on NEET PG rank, category and choice filling?",
      "Are you aware of the reservation and category rules applicable to your profile?",
      "What is the difference between Government, Private, Minority, and NRI seats in Bihar?",
    ],
  },
  chhattisgarh: {
    title: "MD/MS in Chhattisgarh",
    metaTitle: "MD/MS in Chhattisgarh | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Chhattisgarh MD/MS counselling — eligibility, seat categories, reservation, fees, and expert NEET PG guidance.",
    bannerTitle: "Chhattisgarh MD/MS Counselling Guide",
    bannerDescription: "Complete information on eligibility, seat distribution, reservation, and counselling procedure for Chhattisgarh MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Chhattisgarh",
    overviewContent:
      "Chhattisgarh offers MD/MS seats through its state counselling process across government and private medical colleges. With expanding PG capacity and improving healthcare infrastructure, the state offers promising opportunities for NEET PG aspirants seeking quality training at competitive fees.",
    highlights: [
      "State counselling with government and private seats",
      "Growing PG capacity and teaching infrastructure",
      "Clear eligibility and reservation rules",
      "Competitive fee structures across categories",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "How does the Chhattisgarh state counselling process allot MD/MS seats based on NEET PG rank and category?",
      "Are you aware of the reservation, institutional, and NRI quota rules applicable to your profile?",
      "Which seat category gives you the best chance of securing your preferred branch in Chhattisgarh?",
    ],
  },
  "west-bengal": {
    title: "MD/MS in West Bengal",
    metaTitle: "MD/MS in West Bengal | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to West Bengal MD/MS counselling — eligibility, seat categories, reservation, fees, and expert NEET PG guidance.",
    bannerTitle: "West Bengal MD/MS Counselling Guide",
    bannerDescription: "Complete information on eligibility, seat distribution, reservation, and counselling procedure for West Bengal MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in West Bengal",
    overviewContent:
      "West Bengal offers MD/MS seats through the West Bengal Medical Counselling Committee (WBMCC) across renowned government and private medical colleges. With prestigious institutions and strong clinical exposure, the state is a popular destination for NEET PG aspirants.",
    highlights: [
      "State counselling conducted by the West Bengal Medical Counselling Committee",
      "Renowned government medical colleges with high clinical exposure",
      "Clear reservation and eligibility framework",
      "Competitive fee structures across categories",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "Do you know how the West Bengal state merit list is prepared and seats are allotted based on NEET PG rank?",
      "Are you aware of the reservation, institutional, and NRI quota rules applicable to your profile?",
      "What is the difference between Government Quota and Management Quota seats in West Bengal?",
    ],
  },
  uttarakhand: {
    title: "MD/MS in Uttarakhand",
    metaTitle: "MD/MS in Uttarakhand | PG Medical Admissions | ADCB Consultancy",
    metaDescription: "Complete guide to Uttarakhand MD/MS counselling — eligibility, seat categories, reservation, fees, and expert NEET PG guidance.",
    bannerTitle: "Uttarakhand MD/MS Counselling Guide",
    bannerDescription: "Complete information on eligibility, seat distribution, reservation, and counselling procedure for Uttarakhand MD/MS admissions.",
    bannerImage: "/courses/md-ms.jpg",
    overviewTitle: "MD/MS in Uttarakhand",
    overviewContent:
      "Uttarakhand offers MD/MS seats through its state counselling process across government and private medical colleges. With a growing number of PG seats and an improving healthcare network, the state offers promising opportunities for NEET PG aspirants.",
    highlights: [
      "State counselling with government and private seats",
      "Growing PG capacity and teaching infrastructure",
      "Clear eligibility and reservation rules",
      "Competitive fee structures across categories",
    ],
    previewTitle: "Introduction",
    previewPoints: [
      "How does the Uttarakhand state counselling process allot MD/MS seats based on NEET PG rank and category?",
      "Are you aware of the reservation, institutional, and NRI quota rules applicable to your profile?",
      "Which seat category gives you the best chance of securing your preferred branch in Uttarakhand?",
    ],
  },
};
