export interface MdMsGuideSection {
  id: string;
  label: string;
  questions: string[];
}

export const mdmsGuideData: Record<string, MdMsGuideSection[]> = {
  chhattisgarh: [
    {
      id: "general-information",
      label: "A. General Information",
      questions: [
        "Can I submit more than one CGDME counselling application? What happens if I do?",
        "What happens if I enter incorrect information during registration? Can it be corrected later?",
        "Can CGDME change my Name, Date of Birth, Category or other details after registration?",
        "Will registering for CGDME counselling guarantee me an MD/MS seat?",
        "What happens if I get a Round 2 seat but don't join the allotted college?",
        "Can I reject my allotted seat without losing my chance in further counselling rounds?",
        "What happens if I generate the allotment letter but fail to take admission?",
        "How do I confirm whether I am eligible or have the required domicile status before choice filling?",
        "How can I avoid choosing a medical college without knowing its complete fee structure and additional charges?",
        "What happens if I miss an important counselling update because CGDME does not contact candidates individually?",
      ],
    },
    {
      id: "documentation",
      label: "B. Documentation",
      questions: [
        "Can one missing or outdated document make me ineligible for all further counselling rounds?",
        "What is the deadline for getting my caste, EWS, OBC-NCL and other certificates ready?",
        "Can I participate in the next counselling round if my documents fail scrutiny?",
        "Is a disability certificate from a District Medical Board valid for PwBD quota admission?",
        "Which authority must issue my PwBD disability certificate to claim a medical seat?",
        "Are your documents fully correct and valid for NEET PG counselling—or could one mistake cost you your seat?",
      ],
    },
    {
      id: "counselling-rounds",
      label: "C. Counselling Rounds",
      questions: [
        "Should I Accept or Reject my Round 1 seat to get a better MD/MS option?",
        "What happens if I generate my allotment letter but fail to take admission?",
        "Can I reject a Round 1 seat and still participate in Round 2 counselling?",
        "If I reject my Round 2 seat, can I participate in the Mop-Up Round?",
        "Will I lose my security deposit if I don't join a Round 2 allotted seat?",
        "What happens if my documents fail scrutiny after I am allotted a seat?",
        "Who is eligible to participate in the Mop-Up Round—and who is excluded?",
        "Can I get an MD/MS seat in the Stray Vacancy Round without fresh registration?",
        "What happens if I am allotted a seat in the Mop-Up or Stray Vacancy Round?",
        "Which counselling decision could permanently end my chance of getting a better seat?",
      ],
    },
  ],
  uttarakhand: [
    {
      id: "eligibility-quota",
      label: "A. Eligibility, Quota & Admission Guide",
      questions: [
        "Who is eligible for Uttarakhand State Quota PG seats?",
        "Can non-Uttarakhand MBBS graduates apply for PG seats in Uttarakhand?",
        "What is the difference between State Quota and All India Open Quota?",
        "Can candidates from other states get MD/MS seats in Uttarakhand Private Medical Colleges?",
        "What are the internship and medical council registration requirements?",
        "Are in-service PMHS Medical Officers eligible for DNB & Diploma seats?",
      ],
    },
    {
      id: "reservation",
      label: "B. Reservation: Quota, Domicile & Category Benefits",
      questions: [
        "Who can claim reservation under Uttarakhand State Quota?",
        "What are the SC, ST, OBC & EWS reservation percentages?",
        "Does reservation apply to All India Open Quota seats?",
        "Can women, PwBD, Defence Ward & Orphan candidates get additional reservation benefits?",
        "What documents are mandatory to claim Uttarakhand reservation benefits?",
        "Can an expired OBC-NCL certificate cost you your reserved seat?",
      ],
    },
    {
      id: "seat-conversion",
      label: "C. Seat Conversion & Remote Area Weightage Benefits",
      questions: [
        "What happens if eligible candidates are unavailable in a reserved sub-category?",
        "Can reserved seats be converted to Open/Unreserved seats?",
        "What is the exact order of category-wise seat conversion in Uttarakhand?",
        "In which counselling round does seat conversion take place?",
        "Can in-service doctors from remote areas get additional NEET PG weightage marks?",
        "How can remote-area service doctors claim additional weightage benefits?",
      ],
    },
    {
      id: "colleges-bond",
      label: "D. Colleges, Seat Availability & Government Service Bond",
      questions: [
        "Which Government & Private Medical Colleges offer MD/MS seats in Uttarakhand?",
        "Which colleges offer State Quota and All India Open Quota seats?",
        "Can you get subsidised PG fees by signing a Uttarakhand service bond?",
        "What are the service bond conditions for Government Medical College seats?",
        "How many years of service are required under the Uttarakhand bond?",
        "What happens if you fail to submit the required bond documents?",
      ],
    },
    {
      id: "documents-fees",
      label: "E. Admission Documents, Fees & Refund Rules",
      questions: [
        "What documents are mandatory to secure your allotted PG seat?",
        "What extra documents are required for Reserved, PwD & In-Service candidates?",
        "How and when do you need to pay your PG admission fees?",
        "What happens if you want to quit your allotted PG seat?",
        "Can you get a refund after leaving your allotted college?",
        "How much fee is deducted from your refund, and what other charges apply?",
      ],
    },
    {
      id: "disqualification",
      label: "F. Disqualification, Document Verification & Legal Risks",
      questions: [
        "Can incorrect information permanently disqualify you from NEET PG counselling?",
        "What happens if false documents are discovered after admission?",
        "Can your PG admission be cancelled retrospectively?",
        "Could submitting incorrect information lead to legal action?",
        "Who is responsible if counselling rules or information change unexpectedly?",
        "Where can you legally challenge a dispute related to Uttarakhand NEET PG counselling?",
      ],
    },
  ],
  "himachal-pradesh": [
    {
      id: "introduction",
      label: "A. Introduction",
      questions: [
        "Who is eligible for Himachal Pradesh State Quota MD/MS/DNB seats?",
        "Can Non-Himachal candidates apply for PG seats in private medical colleges?",
        "How are MD/MS/DNB seats allotted through Centralized Counselling?",
        "Which Government & Private Medical Colleges are included in the counselling?",
        "What are the bond, stipend, hostel & fee rules for each college?",
        "Can you get an MD/MS/DNB seat in Himachal Pradesh with your NEET-PG rank?",
      ],
    },
    {
      id: "incentive",
      label: "B. Incentive & Sponsorship Rules",
      questions: [
        "Are you an in-service GDO? Find out how much NEET-PG incentive you can claim.",
        "How many years of rural or remote service are required to become eligible?",
        "Can your service in multiple districts be combined to meet the eligibility criteria?",
        "How is your incentive percentage calculated—and can it boost your NEET-PG merit?",
        "Does your previous GDO service count if you have had a break in service?",
        "Are you eligible for an Incentive Certificate and State Quota MD/MS seat in Himachal Pradesh?",
      ],
    },
    {
      id: "admission-eligibility",
      label: "C. Admission Eligibility: State Quota, NRI & NRI-Sponsored Seats",
      questions: [
        "Are you eligible for a 50% State Quota MD/MS seat in Himachal Pradesh?",
        "Can Non-Himachali candidates get MD/MS seats in Himachal Pradesh?",
        "Who can apply for Management Quota seats in private medical colleges?",
        "Are you eligible for NRI or NRI-Sponsored MD/MS seats?",
        "Who can sponsor you under the NRI-Sponsored category—and what proof is required?",
        "What happens to vacant NRI, SC/ST and reserved-category seats after Round 3?",
      ],
    },
    {
      id: "seat-distribution",
      label: "D. College & Specialty-Wise Seat Distribution",
      questions: [
        "Which MD/MS specialties are available in Himachal Pradesh Government Medical Colleges?",
        "How many State Quota seats are available in your preferred specialty?",
        "Which colleges offer the highest number of seats in your desired branch?",
        "What is the GDO vs Direct Candidate seat distribution for each specialty?",
        "Can you access MD/MS seats in private colleges through State, Management or NRI Quota?",
        "Based on your NEET-PG rank, which college and specialty could you target?",
      ],
    },
    {
      id: "reservation",
      label: "E. Reservation & Documents",
      questions: [
        "Which reservation category can give you an advantage in Himachal PG counselling?",
        "Are you eligible for SC, ST, EWS, PwD or Single Girl Child reservation?",
        "Can a Single Girl Child claim a reserved MD/MS seat in a Government Medical College?",
        "Do you qualify for EWS reservation—and what income and asset limits apply?",
        "Which certificates and documents are mandatory for PG counselling registration?",
        "Could one missing or incorrect document affect your MD/MS/DNB admission?",
      ],
    },
    {
      id: "online-application",
      label: "F. Online Application & Payment",
      questions: [
        "How do you fill the Himachal Pradesh MD/MS/DNB counselling form correctly?",
        "What photo, signature and document specifications must you follow?",
        "Could a mismatch in your NEET-PG details stop you from registering?",
        "Are you required to select Management Quota while applying for State Quota?",
        "Can you change your category or edit the application after final submission?",
        "How can you ensure your application is successfully submitted and avoid rejection?",
      ],
    },
    {
      id: "counselling-rounds",
      label: "G. Counselling: Round-Wise Strategy, Seat Allotment & Upgradation",
      questions: [
        "How does Himachal Pradesh MD/MS/DNB counselling allocate seats based on your rank and choices?",
        "What happens after Round 1—and how can you upgrade your allotted seat in Round 2?",
        "How much Token Fee is required for Round 2, and when can you get it refunded?",
        "Can you choose colleges or specialties that are not currently shown in the vacancy list?",
        "What are the rules for Round 3 and Stray Round—and can you still participate without a fresh registration?",
        "Can your allotted seat be cancelled due to document issues, ineligibility, or failure to report on time?",
      ],
    },
    {
      id: "bond-commitment",
      label: "H. Bond, Service Commitment, Penalties & Stipend",
      questions: [
        "How long must you serve Himachal Pradesh after completing MD/MS/DNB?",
        "What is the ₹40 lakh bond—and when can it be enforced?",
        "Can you leave the PG course after the admission cut-off date without a ₹10 lakh penalty?",
        "What happens if you violate the mandatory service bond after PG?",
        "Will you receive a stipend or full salary during your MD/MS/DNB course?",
        "Can you pursue Senior Residency, Super-Speciality or a second PG during your mandatory service period?",
      ],
    },
    {
      id: "bond-fees-stipend",
      label: "I. Bond, Fees, Stipend & Admission Rules",
      questions: [
        "How long do you have to serve Himachal Pradesh after completing PG?",
        "What happens if you violate the mandatory service bond?",
        "Is there a ₹40 Lakh bond—and when can it be enforced?",
        "What happens to your original MBBS degree after admission?",
        "What is the ₹10 Lakh penalty for leaving PG midway?",
        "How much stipend can you receive during MD/MS/DNB?",
        "Can you pursue a second PG, Super Specialty or Senior Residency after PG?",
        "What happens if you leave your PG course after the final admission cut-off date?",
        "What are the fees and hostel charges in Himachal Pradesh Government Medical Colleges?",
        "What are the tuition fees for MD/MS specialties at MMU, Solan?",
      ],
    },
  ],
  "west-bengal": [
    {
      id: "general-information",
      label: "A. General Information",
      questions: [
        "Who is eligible for West Bengal NEET PG 2025 State Quota, Management Quota & NRI Quota seats?",
        "Are you eligible for West Bengal NEET PG 2025 counselling based on your NEET PG rank and category?",
        "How does the West Bengal NEET PG 2025 reservation system work for UR, EWS, OBC-A, OBC-B, SC, ST & PwD candidates?",
        "Are you an in-service doctor? Do you qualify for reserved State Quota MD/MS/Diploma seats?",
        "What happens to vacant State Quota or Open Quota PG medical seats in West Bengal?",
        "Confused about your chances of getting an MD/MS/DNB seat in West Bengal?",
      ],
    },
    {
      id: "eligibility-reservation",
      label: "B. Eligibility and Reservation",
      questions: [
        "What is the minimum NEET PG 2025 percentile required for your category in West Bengal?",
        "Can an OBC candidate from another state claim OBC reservation in West Bengal State Quota?",
        "Is your West Bengal OBC-NCL certificate valid for NEET PG 2025 counselling?",
        "Could a missing or invalid caste certificate change your category to Unreserved during counselling?",
        "Are you eligible for EWS reservation in West Bengal State Quota—and what certificate do you need?",
        "Do you qualify for the 5% PwD reservation, and which benchmark disability certificate is accepted?",
      ],
    },
    {
      id: "admission-discontinuation",
      label: "C. Admission and Discontinuation",
      questions: [
        "Can you join West Bengal NEET PG counselling if you're already pursuing another PG course?",
        "Have you completed a PG Diploma? Could it affect your eligibility for another PG course?",
        "What are the ₹5 lakh and ₹2 lakh penalties for discontinuing an MD/MS or PG Diploma course?",
        "After completing PG, are you required to serve the West Bengal Government under a service bond?",
        "Can you change your category from UR/EWS/OBC to OBC-A or OBC-B during West Bengal counselling?",
        "What happens if your caste, PwD, domicile or service documents fail verification during counselling?",
      ],
    },
    {
      id: "open-inservice",
      label: "D. Open, In-Service & Other Service Category Eligibility",
      questions: [
        "Who can apply for West Bengal NEET PG State Quota as an Open Category candidate?",
        "Did you complete MBBS outside West Bengal? Can you still claim State Quota eligibility through domicile?",
        "Are you eligible for In-Service Quota after completing 3 years of Government service?",
        "Does rural, remote or difficult-area service make you eligible for West Bengal In-Service Quota?",
        "Is Trainee Reserve (TR) guaranteed for every In-Service candidate who gets a PG seat?",
        "Are you a Government or Semi-Government employee? Can you apply under the Other Service Category?",
      ],
    },
    {
      id: "private-mgmt-quota",
      label: "E. Private Management Quota Eligibility & Admission Guide",
      questions: [
        "Can you apply for West Bengal Private Management Quota without a West Bengal domicile?",
        "Did you qualify NEET PG 2025? Are you eligible for Management Quota seats in West Bengal private medical colleges?",
        "What NEET PG 2025 cut-off applies to you for Private Management Quota admission?",
        "Do Private Management Quota seats have reservation for SC, ST, OBC, EWS or PwD candidates?",
        "What are the fees, bonds and bank guarantee requirements for Private Management Quota seats?",
        "Which West Bengal private medical colleges offer Management Quota seats—and what are your chances of getting one?",
      ],
    },
    {
      id: "nri-quota",
      label: "F. NRI Quota Eligibility, Documents & Counselling",
      questions: [
        "Are you eligible for NRI Quota MD/MS seats in West Bengal—and what documents do you need?",
        "Can NRI, PIO and OCI candidates apply for West Bengal NEET PG NRI Quota seats?",
        "Can you choose NRI Quota and still participate in State Quota or Management Quota counselling?",
        "What happens if your NRI sponsorship or supporting documents fail verification after seat allotment?",
        "Could choosing NRI Quota incorrectly cancel your candidature from the entire counselling process?",
        "How do NRI Quota seat allotment, choice filling, fees and document verification work in West Bengal?",
      ],
    },
    {
      id: "document-verification",
      label: "G. Document Verification, Seat Allotment & Surrender Rules",
      questions: [
        "What happens if your domicile, MBBS, caste or in-service documents fail verification?",
        "Can you change your category and re-enter the next counselling round after document rejection?",
        "Could an invalid caste or PwD certificate cancel your allotted seat?",
        "Missed Round 1 or failed to report after allotment? Can you still participate in Round 2?",
        "What happens if you surrender your allotted PG seat in Round 1, Round 2 or Round 3?",
        "Can you upgrade your seat in the next round—and what happens to your previous allotment?",
      ],
    },
    {
      id: "round-wise",
      label: "H. Round-Wise Counselling Process & Seat Allotment Rules",
      questions: [
        "What are the exact steps from NEET PG registration to final admission in West Bengal?",
        "Is physical document verification mandatory—and what happens if you miss it?",
        "Why is choice locking so important, and can your unlocked choices be considered for seat allotment?",
        "Got a seat in Round 1? Can you participate in Round 2 and upgrade your PG seat?",
        "What happens if your allotted seat is cancelled due to inadequate documents? Can you re-enter counselling?",
        "Missed your chance in earlier rounds? Can you still secure a seat through Round 3 or Online Stray Vacancy Round?",
      ],
    },
    {
      id: "online-counselling",
      label: "I. Online Counselling Process & Seat Conversion Rules",
      questions: [
        "How do you register and complete fee payment for West Bengal NEET PG counselling without making a costly mistake?",
        "Can you edit your registration details after payment—and what happens if you enter incorrect information?",
        "What documents are required for physical verification, and what happens if your documents are not accepted?",
        "How should you arrange your choices to maximise your chances of getting your preferred MD/MS/DNB seat?",
        "Can your saved choices be changed after locking—and what happens if you forget to lock them?",
        "Which vacant reserved, Management or NRI seats can be converted in Round 3 or the Stray Vacancy Round?",
      ],
    },
    {
      id: "nri-documents",
      label: "J. NRI Documents, Special Seats & Candidature Cancellation Rules",
      questions: [
        "What documents are required to successfully claim an NRI Quota PG medical seat in West Bengal?",
        "Can NRI candidates directly participate in choice filling and seat allotment without pre-choice document verification?",
        "What is the counselling process for NRI Quota seats—from choice filling to final admission?",
        "Who can benefit from the 2 special PG seats reserved at IPG&MER under the Rai Bahadur Sukhlall Chandanmull Kamani Trust?",
        "Could providing false, incomplete or fabricated information lead to immediate cancellation of your PG admission?",
        "What happens if incorrect information or document discrepancies are discovered after your admission?",
      ],
    },
  ],
  pondicherry: [
    {
      id: "important-points",
      label: "A. Important Points",
      questions: [
        "How do I choose the right MD/MS college and course preferences to maximise my chances of getting a seat?",
        "What happens if I miss a CENTAC deadline or fail to submit the right course preferences?",
        "Which documents are mandatory—and what mistakes can lead to rejection of my application?",
        "Am I eligible for reservation benefits, and how does category-wise seat allocation work in Puducherry?",
        "What are the actual tuition fees, additional fees and bond requirements for each MD/MS college?",
        "What should I do after getting an allotment to ensure I don't lose my MD/MS seat?",
      ],
    },
    {
      id: "introduction",
      label: "B. Introduction",
      questions: [
        "Am I eligible for Puducherry MD/MS counselling—and which quota can I apply under?",
        "Should I apply through CENTAC or MCC—and which counselling process is right for me?",
        "What is the difference between Government, Management and Telugu Minority Quota seats?",
        "How do I choose the right college and course preferences without losing my best chance of allotment?",
        "What are the actual fees, additional charges and financial commitments before I lock my choices?",
        "What happens if I make a mistake in my application or submit incorrect information?",
        "How do I track every counselling round, merit list and allotment update without missing a critical deadline?",
        "What strategy should I follow with my NEET PG rank to maximise my chances of getting the right MD/MS seat?",
      ],
    },
    {
      id: "seat-information",
      label: "C. Seat Information",
      questions: [
        "With your NEET PG rank, which Puducherry MD/MS seats can you realistically target?",
        "Are you eligible for Government Quota, Management Quota, or Minority Quota seats?",
        "What is the difference between GQ, MQ, MQT and AGE seats—and which one is best for you?",
        "Can non-Puducherry residents apply for Management Quota seats in Puducherry?",
        "How many MD/MS seats are actually available through CENTAC—and how many are filled through MCC?",
        "Can Management Quota seats in PIMS and SMVMCH be available to you from Round 1?",
        "Are you eligible for Telugu Minority Quota—and what documents are required to prove your eligibility?",
        "Which Puducherry medical college and speciality should you choose based on your rank, category and budget?",
      ],
    },
    {
      id: "eligibility-residence",
      label: "D. Eligibility and residence criteria",
      questions: [
        "Are you actually eligible for Puducherry Government Quota MD/MS seats?",
        "Does studying in Puducherry make you eligible for Government Quota—or is a 5-year residence required?",
        "Can candidates from other states apply for MD/MS seats in Puducherry? If yes, under which quota?",
        "Do you qualify as a Puducherry resident through your parents, education, or family background?",
        "What happens if you are eligible for Government Quota in both Puducherry and another state?",
        "Can claiming Government Quota in another state make you ineligible for Puducherry Government Quota?",
        "What documents and affidavits are required to prove your Puducherry residence eligibility?",
        "Could a wrong nativity claim lead to cancellation of your MD/MS admission or even legal action?",
        "Are you truly eligible for Puducherry Government Quota—or are you making a costly assumption?",
        "Eligible for Government Quota in two states? Which one should you choose for your MD/MS admission?",
        "Could one wrong nativity claim cost you your MD/MS seat? Know the rules before you apply.",
      ],
    },
    {
      id: "reservation-rules",
      label: "E. Reservation and seat-allocation rules",
      questions: [
        "What reservation category can you claim—and how does it affect your MD/MS seat chances?",
        "Are you eligible for Government Quota seats based on your Puducherry region and category?",
        "What is the difference between Vertical and Horizontal Reservation—and how can both impact your allotment?",
        "Can an OBC, MBC, BCM, SC or ST candidate also compete for an Unreserved (UR) seat?",
        "What happens to reserved seats that remain vacant until Round 3?",
        "Can Telugu Minority Quota seats become available to All India Management Quota candidates?",
        "Do you qualify for PwD, Freedom Fighter, Ex-Servicemen or Sports Quota—and what documents are required?",
        "Could a missing or incorrect reservation certificate cost you your chance of getting your preferred MD/MS seat?",
      ],
    },
    {
      id: "application-process",
      label: "F. Application process and document requirements",
      questions: [
        "How do you fill your CENTAC application correctly without making a costly mistake?",
        "What are the mandatory documents you must upload to complete your MD/MS application?",
        "Could an incorrect or incomplete document upload affect your MD/MS counselling application?",
        "How do you correctly fill and lock your college and course preferences to maximise your chances?",
        "What are the exact file size and format requirements for your photo, signature and certificates?",
        "What should you verify before making the final payment and submitting your CENTAC application?",
      ],
    },
    {
      id: "quota-documents",
      label: "G. Government and Management Quota document requirements",
      questions: [
        "Are your certificates valid for the 2025 Puducherry MD/MS counselling process?",
        "Do you need a Residence Certificate, Community Certificate—or both for Government Quota?",
        "Are you required to submit a Dual Nativity Affidavit—and what happens if you claim Government Quota elsewhere?",
        "Do you qualify for Freedom Fighter, Ex-Serviceman, Telugu Minority, PwD or Sports Quota benefits?",
        "Are you applying under Management Quota? Do you need a recently issued All India OBC/SC/ST certificate?",
        "Are you an OCI candidate—and does the date your OCI card was granted affect your eligibility?",
        "Is your certificate date valid—or could an outdated certificate affect your MD/MS Government Quota application?",
        "Are you eligible for Puducherry Government Quota without triggering Dual Nativity issues?",
        "Management Quota or Government Quota—which documents do you need to secure your MD/MS seat?",
      ],
    },
    {
      id: "registration-fee",
      label: "H. Registration fee and forfeiture rules",
      questions: [
        "How much money could you lose if you don't join your allotted MD/MS seat?",
        "Which counselling round carries the highest financial risk if you change your mind?",
        "Can you resign from an MD/MS seat after joining in Round 1, 2 or 3?",
        "What is the difference in registration fees and forfeiture rules between Government and Management Quota?",
        "Could missing a Stray Round seat lead to more than just losing your registration fee?",
        "Before paying the registration fee, do you know exactly what happens if you don't join or resign?",
        "Could you lose up to the full tuition fee—and face a counselling ban—if you don't join your Stray Round seat?",
        "Planning to upgrade your MD/MS seat? Do you know when your registration fee can be forfeited?",
        "Government Quota or Management Quota—which option carries the bigger financial risk if you don't join?",
      ],
    },
    {
      id: "forfeiture-rules",
      label: "I. Forfeiture Rules",
      questions: [
        "What happens if I don't join my Round 2 or Round 3 allotted seat?",
        "If I resign from a seat after joining, will I lose my deposit or fee?",
        "What are the consequences of not joining a Stray Round seat?",
        "Can a wrong document or incorrect information get my admission cancelled?",
        "Can I change my college or course preferences after submitting them?",
        "How can I avoid losing my money or eligibility due to a counselling mistake?",
      ],
    },
    {
      id: "merit-list",
      label: "J. Merit list & online counselling",
      questions: [
        "How is my NEET PG rank used to prepare the CENTAC Merit List?",
        "What is the difference between the Draft, Revised Draft and Final Merit List?",
        "Can I challenge or correct an error in the CENTAC Merit List?",
        "What happens if the NEET PG cut-off is lowered after the counselling process begins?",
        "Which counselling round gives me the best chance of securing my preferred MD/MS seat?",
        "What are the different rules and risks in Round 1, Round 2, Round 3 and Stray Round?",
      ],
    },
    {
      id: "general-instructions",
      label: "K. General Instructions for online counselling",
      questions: [
        "Can I upgrade my MD/MS seat after Round 1—and what happens to my old seat?",
        "What happens if I get a seat but fail to join within the given deadline?",
        "Can I resign from my allotted seat without losing money? Which round matters?",
        "What is the biggest risk of choosing a seat in Round 3 or the Stray Round?",
        "Can I change my college through mutual transfer after getting a seat?",
        "If I am not allotted a seat in one round, can I still participate in the next round?",
      ],
    },
    {
      id: "eligibility-online",
      label: "L. Eligibility for Online Counselling",
      questions: [
        "Who is eligible to participate in each CENTAC counselling round?",
        "Can I participate in Round 2 if I skipped Round 1?",
        "If I resign from my Round 1 or Round 2 seat, can I still enter Round 3?",
        "Who can participate in the Stray Round—and who is completely barred?",
        "Can I participate in the Stray Round if I have joined an MD/MS seat elsewhere?",
        "What happens if I get a Round 3 seat—can I still try for a better seat in the Stray Round?",
      ],
    },
    {
      id: "distribution-eligibility",
      label: "M. Distribution & Eligibility criteria for MD/MS",
      questions: [
        "Am I eligible for MD/MS admission if I completed my MBBS abroad?",
        "What are the mandatory requirements to qualify for MD/MS admission?",
        "Have I completed my internship before the deadline—and am I eligible to apply?",
        "Can I pursue another PG degree if I already hold an MD/MS degree?",
        "Can I apply for MD/MS if I am currently pursuing another PG course?",
        "Is there any upper age limit for MD/MS admission?",
      ],
    },
  ],
  haryana: [
    {
      id: "basic-eligibility",
      label: "A. Basic and State Eligibility",
      questions: [
        "Am I eligible for Haryana MD/MS counselling with my NEET PG rank?",
        "Can a non-Haryana candidate get an MD/MS seat in Haryana?",
        "Can I apply for Haryana State Quota without a Haryana domicile?",
        "Which Haryana MD/MS seats are open to candidates from other states?",
        "Am I eligible for Private, Management or NRI quota seats in Haryana?",
        "Which quota gives me the best chance of securing an MD/MS seat in Haryana?",
      ],
    },
    {
      id: "seat-categories",
      label: "B. Seat categories",
      questions: [
        "Which MD/MS seat category am I eligible for in Haryana?",
        "Can I get an MD/MS seat in Haryana without a State Quota seat?",
        "Can non-Haryana candidates secure seats through Management Quota?",
        "What is the difference between Open Merit and Management Quota seats?",
        "Am I eligible for NRI or NRI-Sponsored MD/MS seats?",
        "Which seat category gives me the best chance of getting my preferred speciality?",
      ],
    },
    {
      id: "merit-rounds",
      label: "C. Merit and Counselling rounds",
      questions: [
        "Will my NEET PG rank get me the MD/MS seat I want?",
        "How does my NEET PG rank affect my chances of getting a preferred speciality?",
        "Which colleges and specialities should I choose during choice filling?",
        "How can I maximise my chances through strategic choice filling?",
        "What happens if I don't get a seat in the first counselling round?",
        "Can I still secure an MD/MS seat in the later counselling rounds?",
      ],
    },
    {
      id: "choice-filling",
      label: "D. Choice filling and Documentation",
      questions: [
        "How should I fill my choices to maximise my chances of getting a seat?",
        "Which college and speciality should I prioritise based on my NEET PG rank?",
        "Can the wrong choice-filling strategy cost me my preferred MD/MS seat?",
        "Which documents are mandatory for Haryana MD/MS counselling?",
        "Could a missing or incorrect document affect my seat allotment?",
        "What documents do I need based on my quota, category, or domicile?",
      ],
    },
    {
      id: "fee-bond",
      label: "E. Fee Structure & Bond/Service obligations",
      questions: [
        "What is the actual cost of MD/MS admission in Haryana?",
        "How much will I need to pay for Government vs Private colleges?",
        "What are the fees for Open Merit, Management and NRI seats?",
        "Are there any hidden costs beyond the tuition fee?",
        "Will I have to sign a bond or fulfil a service obligation?",
        "How do bond rules differ between Government and Private colleges?",
      ],
    },
    {
      id: "reservation",
      label: "F. Reservation",
      questions: [
        "Am I eligible for EWS reservation in Haryana MD/MS admissions?",
        "Who can claim the 10% EWS reservation in Haryana?",
        "Can I avail EWS reservation if I belong to SC or BC categories?",
        "What documents are required to claim EWS reservation?",
        "Does EWS reservation apply to Government and Government-Aided medical colleges?",
        "Will my EWS status affect my chances of getting an MD/MS seat?",
      ],
    },
    {
      id: "income-assets",
      label: "G. Income Assets",
      questions: [
        "Who is actually eligible for EWS reservation in Haryana?",
        "Does my family income qualify me for EWS benefits?",
        "Can property ownership make me ineligible for EWS reservation?",
        "Which family members and assets are considered when determining EWS eligibility?",
        "How and where can I obtain the EWS Income & Asset Certificate?",
        "What happens if my EWS certificate is found to be incorrect or invalid?",
      ],
    },
  ],
  punjab: [
    {
      id: "general-instructions",
      label: "A. General Instructions",
      questions: [
        "Who is eligible to participate in Punjab MD/MS 2025 State Counselling?",
        "Is NEET PG qualification alone enough to secure admission in Punjab?",
        "What are the most common mistakes that can lead to rejection of your Punjab MD/MS application?",
        "Can you change your reservation category or quota after registration in Punjab counselling?",
        "How are Punjab MD/MS seats allotted, and what factors decide your college and specialty?",
        "When will the security deposit be refunded, and what refund mistakes should candidates avoid?",
        "What documents and eligibility proofs must you keep ready before reporting to the allotted college?",
        "Which official updates should every Punjab MD/MS aspirant regularly track to avoid missing important counselling events?",
      ],
    },
    {
      id: "nri-conditions",
      label: "B. Fees, Eligibility & instructions for NRI candidates and the conditions",
      questions: [
        "What is the application fee for Punjab MD/MS 2025, and is it refundable?",
        "Who is eligible to apply for NRI Quota MD/MS seats in Punjab?",
        "What documents are mandatory to obtain the BFUHS NRI Eligibility/Equivalency Certificate?",
        "Can NRI candidates pay the MD/MS tuition fee in instalments, and what are the payment conditions?",
        "Does qualifying NEET PG alone guarantee admission to Punjab MD/MS counselling?",
        "How is the final eligibility for Punjab MD/MS admission verified after seat allotment?",
        "Who decides eligibility for Minority Quota MD/MS seats in Punjab?",
        "What is the complete step-by-step process of Punjab MD/MS Round 1 online counselling, from registration to joining the college?",
      ],
    },
    {
      id: "counselling",
      label: "C. Punjab MD/MS 2025 Counselling",
      questions: [
        "How can you apply for Punjab MD/MS 2025 without making mistakes that lead to rejection?",
        "What is the complete eligibility process for NRI Quota MD/MS admissions in Punjab?",
        "Can your NEET PG rank alone guarantee an MD/MS seat in Punjab?",
        "How does Punjab allot MD/MS seats based on your preferences, merit, and quota?",
        "Which original documents are compulsory at the time of reporting and admission?",
        "What are the security deposit, refund, and forfeiture rules in Punjab MD/MS counselling?",
        "Can you upgrade your seat in Round 2 or Round 3, and what are the conditions?",
        "What penalties can result in losing your allotted MD/MS seat or security deposit in Punjab counselling?",
      ],
    },
  ],
  bihar: [
    {
      id: "important-questions",
      label: "A. Important Questions Doctors Should Know",
      questions: [
        "Can Non-Bihar Candidates Get MD/MS Admission Opportunities in Bihar Private Medical Colleges Through NEET PG 2025 Counselling?",
        "What Are the MD/MS and DNB Seat Opportunities Available in Bihar Government and Private Medical Colleges for NEET PG 2025?",
        "Are NRI Quota Seats Available for MD/MS Admission in Bihar Private Medical Colleges, and Who Can Claim NRI Eligibility?",
        "Can Service Doctors in Bihar Get Additional Benefits Like Incentive Marks or Reserved Seats for PG Medical Admission?",
        "Which Private Medical Colleges in Bihar Offer MD/MS Courses Through BCECEB NEET PG 2025 Counselling?",
        "How Can Doctors Secure the Best MD/MS Branch and College Options During Bihar NEET PG 2025 Counselling?",
      ],
    },
    {
      id: "eligibility",
      label: "B. Eligibility & Admission FAQ",
      questions: [
        "Can Doctors From Other States Apply for MD/MS Admission in Bihar Through NEET PG 2025 Counselling?",
        "Is Bihar MBBS Qualification Mandatory for MD/MS Admission in Bihar, or Are Non-Bihar Candidates Also Eligible?",
        "What Are the Internship Completion and Medical Registration Requirements for Bihar NEET PG 2025 Admission?",
        "Is There Any Maximum Age Limit for Doctors Appearing for Bihar NEET PG 2025 Counselling?",
        "Can Government Service Doctors Apply for Bihar NEET PG Counselling, and What Benefits Are Available for In-Service Candidates?",
        "What Are the Important Rules Regarding PG Training Duration, Registration, and Course Admission After Selection in Bihar?",
      ],
    },
    {
      id: "reservation",
      label: "C. Reservation & Quota FAQs",
      questions: [
        "What Are the Reservation Benefits Available for Bihar Domicile Candidates in MD/MS Admission Through NEET PG 2025?",
        "Can Non-Bihar Candidates Claim SC/ST/EBC/BC/EWS Reservation Benefits in Bihar NEET PG Counselling?",
        "How Are Reserved Category Seats and Unreserved Seats Distributed for MD/MS Admission in Bihar Government Medical Colleges?",
        "Is There Any Special Reservation Benefit Available for Women Candidates in Bihar NEET PG 2025 Counselling?",
        "What Are the Eligibility Criteria and Documents Required to Claim Reserved Category Seats in Bihar PG Medical Counselling?",
        "Are PwD (Disabled Quota) Candidates Eligible for Reserved Seats in Bihar MD/MS Admission, and What Documents Are Required?",
      ],
    },
    {
      id: "counselling-process",
      label: "D. Counselling Process",
      questions: [
        "How Can Doctors Register for Bihar NEET PG 2025 Counselling and Successfully Complete the MD/MS Admission Process?",
        "What Is the Counselling Fee and Security Deposit Required for Government and Private Medical Colleges in Bihar NEET PG 2025?",
        "What Are the Step-by-Step Procedures for Choice Filling, Choice Locking, and Seat Allotment in Bihar PG Medical Counselling?",
        "Can Doctors Claim NRI Quota Seats in Bihar MD/MS Admission, and What Documents Are Required for NRI Eligibility Verification?",
        "What Happens After Seat Allotment in Bihar NEET PG Counselling, and What Documents Are Required for Admission Confirmation?",
        "How Does Merit-Based Seat Allotment Work in Bihar NEET PG 2025, and How Can Doctors Improve Their Chances of Getting Their Preferred MD/MS Seat?",
      ],
    },
    {
      id: "selection-admission",
      label: "E. Selection & Admission Process",
      questions: [
        "How Is the Merit List Prepared for Bihar NEET PG 2025 MD/MS Admission, and How Does NEET PG Rank Affect Seat Allotment?",
        "How Many Counselling Rounds Are Conducted in Bihar NEET PG 2025, and Can Doctors Participate in All Rounds?",
        "How Does Online Choice Filling and Seat Allotment Work in Bihar PG Medical Counselling 2025?",
        "What Are the Minimum NEET PG Qualifying Criteria Required for MD/MS Admission in Bihar?",
        "Can a Doctor Already Pursuing MD/MS or PG Diploma Apply Again for Bihar NEET PG Counselling 2025?",
        "What Are the Important Admission Rules, Bond Requirements, and Joining Conditions After Getting a PG Seat in Bihar Government Medical Colleges?",
      ],
    },
    {
      id: "general-instructions",
      label: "F. General Instructions & Admission Rules",
      questions: [
        "What Are the Important Rules Doctors Must Follow to Avoid Rejection During Bihar NEET PG 2025 Counselling?",
        "Is Physical Presence Mandatory for Document Verification and Counselling in Bihar MD/MS Admission Process?",
        "What Happens If a Candidate Submits Incorrect Documents or Provides Wrong Information During Bihar NEET PG Counselling?",
        "Can Doctors Lose Their Allocated PG Seat and Security Deposit if They Fail to Join Within the Given Time?",
        "Are There Any Risks of Paying Agents for Direct MD/MS Seats in Bihar Medical Colleges Outside Official Counselling?",
        "When Will the Security Deposit Be Refunded After Bihar NEET PG 2025 Counselling, and What Are the Important Refund Rules?",
      ],
    },
    {
      id: "pwd-quota",
      label: "G. PwD (Persons with Disabilities) Quota & Eligibility",
      questions: [
        "Who Are Eligible for PwD Quota Benefits in Bihar NEET PG 2025 Admission, and What Is the Minimum Disability Percentage Required?",
        "Which Types of Disabilities Are Considered Eligible for MD/MS Admission Under PwD Quota in Medical Courses?",
        "Can Candidates With Physical Disabilities Like Locomotor Disability, Cerebral Palsy, Visual Impairment, or Hearing Impairment Apply for PwD Seats?",
        "What Are the Disability Criteria and Medical Fitness Requirements for Candidates Claiming PwD Reservation in Bihar NEET PG Counselling?",
        "Are Candidates With Intellectual Disabilities, Autism Spectrum Disorders, or Mental Health Conditions Eligible for Medical PG Admission Under PwD Category?",
        "What Documents and Disability Certificates Are Required to Claim PwD Quota Benefits During Bihar NEET PG 2025 Counselling?",
      ],
    },
  ],
  "uttar-pradesh": [
    {
      id: "introduction",
      label: "A. Introduction",
      questions: [
        "Can you upgrade your MD/MS seat till the 3rd Round, and what happens if you join it?",
        "How do the 4 rounds of NEET PG counselling affect your admission chances?",
        "Who is eligible for All India Quota, Deemed University, and NRI PG seats?",
        "Can OCI candidates apply for General and NRI seats in NEET PG 2025 counselling?",
        "What are the latest Supreme Court rules every NEET PG aspirant must know before counselling?",
        "Who conducts NEET PG counselling for AIQ, Deemed Universities, and Stray Vacancy seats, and why does it matter?",
      ],
    },
    {
      id: "candidate-information",
      label: "B. Information for candidates",
      questions: [
        "Can a single mistake during MCC registration lead to cancellation of your MD/MS seat?",
        "When is your NEET PG security deposit forfeited, and can you avoid losing it?",
        "What are Virtual Vacancies, and how can they improve your chances in Round 2?",
        "Why should you verify college fees, bond, and stipend before locking your choices?",
        "Can offline admission or resignation make your PG seat invalid? Here's what every doctor should know.",
        "What are the biggest counselling mistakes that can cost you an MD/MS seat, even after qualifying NEET PG?",
      ],
    },
    {
      id: "aiq",
      label: "C. 50% All India Quota",
      questions: [
        "Can you participate in All India Quota MD/MS counselling without having a state domicile?",
        "What are the 4 rounds of AIQ counselling, and how can each round impact your PG seat chances?",
        "Which MD/MS seats are completely open for candidates across India under the domicile-free AIQ system?",
        "Do you know the reservation benefits available in NEET PG All India Quota counselling?",
        "How can PwD candidates claim 5% reservation in AIQ PG seats, and which certificate is required?",
        "Can vacant reserved category seats get converted into other categories during NEET PG counselling?",
      ],
    },
    {
      id: "deemed-university",
      label: "D. Deemed University, NRI Quota, Minority Quota & OCI eligibility rules",
      questions: [
        "Can you get an MD/MS seat in Deemed Universities through MCC counselling without any state domicile requirement?",
        "How do the 4 rounds of Deemed University counselling impact your chances of securing a PG seat?",
        "Do you have an NRI relative? Find out if you are eligible for NRI Quota MD/MS seats.",
        "Which NRI relatives can sponsor your PG admission, and what documents are required for NRI Quota eligibility?",
        "Can NRI, Jain Minority, and Muslim Minority seats get converted into General Merit seats in later counselling rounds?",
        "Are OCI cardholders eligible for General and NRI category MD/MS seats under MCC counselling 2025?",
      ],
    },
    {
      id: "afms",
      label: "E. AFMS (Armed Forces Medical Services)",
      questions: [
        "Who is eligible for AFMS PG MD/MS counselling through MCC, and what are the different priority categories?",
        "How can Priority III, IV, and V candidates participate in AFMS PG seat allotment?",
        "Can Priority V candidates get an AFMS PG seat before completing their medical fitness evaluation?",
        "What is the medical examination process for AFMS PG candidates after provisional seat allotment?",
        "How does merit, choice filling, and seat availability determine AFMS PG seat allocation?",
        "Where can candidates find the latest AFMS PG counselling updates and important notifications?",
      ],
    },
    {
      id: "central-universities",
      label: "F. Central Universities/Institutes counselling rules",
      questions: [
        "Can you get MD/MS seats in Central Universities through All India Quota without any domicile restriction?",
        "What are the 4 rounds of MCC counselling for Central University PG seats, and how do they impact your admission chances?",
        "Which Central Government medical institutes offer MD/MS seats through the 50% AIQ counselling process?",
        "Do you know the difference between All India Quota seats and Institutional Quota seats in Central Universities?",
        "How can PwD candidates claim 5% reservation in Central University PG seats, and which certificate is mandatory?",
        "Can reserved category seats be converted into other categories during the 3rd round of NEET PG counselling?",
      ],
    },
    {
      id: "dnb",
      label: "G. DNB Counselling guidelines",
      questions: [
        "Can you get a DNB PG seat anywhere in India without any domicile restriction?",
        "Who is eligible for DNB counselling through MCC, and how does NEET PG rank determine seat allotment?",
        "What are the 4 rounds of DNB counselling, and how can each round improve your chances of getting a seat?",
        "Is there any reservation available in DNB seats, and what are the benefits for SC, ST, OBC, EWS, and PwD candidates?",
        "What is the difference between Government DNB and Private DNB reservation policies?",
        "After DNB seat allotment, who handles admission fees and refund-related queries — MCC or NBE?",
      ],
    },
    {
      id: "mcc-registration",
      label: "H. MCC Counselling Registration Process & Round-wise Guidelines",
      questions: [
        "What mistakes during MCC registration can stop you from participating in NEET PG counselling?",
        "Can you upgrade your MD/MS seat from Round 1 to Round 2 or Round 3? Know the rules before choosing.",
        "What happens if you resign, do not report, or fail to join your allotted PG seat in different counselling rounds?",
        "How does Round 3 counselling work, and why is it considered a crucial opportunity for NEET PG aspirants?",
        "Who is eligible for the Stray Vacancy Round, and how can vacant PG seats become available at the final stage?",
        "What are the important documents and reporting requirements to secure your allotted MD/MS seat?",
      ],
    },
    {
      id: "result-admission",
      label: "I. Result & Admission Process",
      questions: [
        "Is the provisional NEET PG counselling result final, or can it change before seat allotment?",
        "What should you do after receiving your MD/MS seat allotment letter from MCC?",
        "Can your MCC allotted PG seat get cancelled during document verification at the college?",
        "Which original documents are mandatory for joining your allotted MD/MS seat?",
        "What category certificates are required to claim reservation benefits during NEET PG admission?",
        "How can you verify fees, bond, stipend, and other college conditions before locking your choices?",
      ],
    },
    {
      id: "counselling-faqs",
      label: "J. Counselling Process & FAQs",
      questions: [
        "How do the 4 rounds of MCC counselling work, and which round can give you the best chance for an MD/MS seat?",
        "Can you participate in Round 2, Round 3, or Stray Vacancy Round if you missed earlier counselling rounds?",
        "What are the common mistakes during choice filling that can affect your NEET PG seat allotment?",
        "How much security deposit is required for AIQ and Deemed University counselling, and when can it be forfeited?",
        "Can you upgrade your allotted MD/MS seat from Round 1 or Round 2 to a better choice in later rounds?",
        "Who is eligible for the final Stray Vacancy Round, and how can vacant PG seats become available at this stage?",
      ],
    },
    {
      id: "refund-security-deposit",
      label: "K. Refund & Security Deposit FAQs",
      questions: [
        "When will my NEET PG counselling security deposit be refunded, and how can I track the refund status?",
        "Will MCC refund my security deposit to a different bank account or card if I made the payment from another account?",
        "What mistakes should I avoid to prevent delays in receiving my counselling security deposit refund?",
        "Can I raise a chargeback request through my bank if my security deposit refund is delayed?",
        "Who is responsible for processing NEET PG counselling refunds, and whom should I contact for refund-related issues?",
        "Can I use an NRI account for counselling fee payment, and how will the refund process work for NRI candidates?",
      ],
    },
  ],
  telangana: [
    {
      id: "regulations",
      label: "A. Regulations",
      questions: [
        "How many MD/MS Management Quota seats will be available in Telangana for the 2025-26 academic year?",
        "Which private medical colleges in Telangana will offer MQ-1, MQ-2 (NRI), and MQ-3 Institutional Quota seats for MD/MS admissions?",
        "When will the official Telangana MD/MS Management Quota seat matrix be released by KNRUHS?",
        "Will newly approved PG medical seats in Telangana private medical colleges also be included in the counselling process?",
        "Are Management Quota MD/MS seats available in both Non-Minority and Minority private medical colleges affiliated with KNRUHS?",
        "How does KNRUHS determine the availability of MD/MS Management Quota seats for NEET PG 2025 candidates?",
      ],
    },
    {
      id: "eligibility",
      label: "B. Eligibility",
      questions: [
        "Who is eligible to apply for Telangana MD/MS Management Quota (MQ-1, MQ-2 NRI & MQ-3 Institutional Quota) seats in 2025?",
        "Can candidates from other states apply for Telangana MD/MS Management Quota seats without Telangana domicile?",
        "What are the NEET PG 2025 qualifying cutoff scores required for Telangana Management Quota admissions?",
        "Are NRI, OCI, and NRI-sponsored candidates eligible for Telangana MD/MS NRI Quota seats?",
        "What MBBS qualification, internship completion, and medical registration requirements are needed for Telangana PG Medical admissions?",
        "Can foreign medical graduates apply for Telangana MD/MS Management Quota seats, and what verification requirements must they fulfill?",
      ],
    },
    {
      id: "application-documents",
      label: "C. Online Application & Document",
      questions: [
        "How do I apply online for Telangana MD/MS 2025 Management Quota (MQ-1, MQ-2 & MQ-3) counselling?",
        "What documents are mandatory for Telangana MD/MS 2025 online registration and certificate verification?",
        "What additional documents are required for NRI Quota (MQ-2) and Institutional Quota (MQ-3) applicants?",
        "Can I complete the Telangana MD/MS application process using my mobile phone, or is a computer required?",
        "How should I upload my certificates, photograph, and signature for the Telangana MD/MS application?",
        "Is the Telangana MD/MS registration and document verification fee refundable if I don't participate in counselling or become ineligible?",
      ],
    },
    {
      id: "merit-list",
      label: "D. Merit List & Seat Distribution",
      questions: [
        "How is the Telangana MD/MS 2025 Management Quota merit list prepared, and what determines your rank?",
        "What is the seat distribution between MQ-1, MQ-2 (NRI), and MQ-3 (Institutional Quota) in Telangana MD/MS admissions?",
        "Who is eligible to apply under MQ-1, MQ-2 (NRI), and MQ-3 Institutional Quota in Telangana?",
        "What are the eligibility requirements and documents needed to claim an NRI (MQ-2) seat in Telangana MD/MS counselling?",
        "Who can apply under the Institutional Quota (MQ-3), and what sponsorship criteria must be fulfilled?",
        "What happens to Muslim Minority MD/MS seats if eligible Minority candidates are not available during Telangana counselling?",
      ],
    },
    {
      id: "counselling-process",
      label: "E. Counselling Process",
      questions: [
        "How does the Telangana MD/MS 2025 counselling process work after the merit list is released?",
        "Why is it important to upload all original certificates during the initial online registration itself?",
        "How will candidates know when Telangana MD/MS web options and counselling rounds begin?",
        "Can the Admission Committee cancel or revise an MD/MS seat allotment after selection?",
        "How is the Telangana MD/MS seat matrix prepared for each counselling round?",
        "Who decides the tuition fee for Telangana MD/MS Management Quota seats, and when is it announced?",
      ],
    },
    {
      id: "admission-rules",
      label: "F. Admission Rules",
      questions: [
        "What bond and penalty conditions must you accept before joining a Telangana MD/MS seat?",
        "What happens if you discontinue your Telangana MD/MS course after the second round of counselling?",
        "Is Senior Residency mandatory after completing an MD/MS course in Telangana?",
        "What are the minimum attendance and leave requirements to remain eligible for the MD/MS final examination?",
        "Can prolonged leave, a break in study, or unauthorized absence affect your MD/MS admission and course duration?",
        "Are MD/MS students in Telangana allowed to do private practice or take up part-time employment during their course?",
      ],
    },
    {
      id: "closure",
      label: "G. Closure of Admissions & Commencement of Course",
      questions: [
        "When is the final date for Telangana MD/MS 2025 admissions, and can it be extended?",
        "Can vacant MD/MS Management Quota seats be filled after the official admission closure date?",
        "What happens to vacant Telangana MD/MS seats after counselling officially ends?",
        "When will the Telangana MD/MS 2025 academic session officially commence?",
        "Is the MD/MS course duration calculated from your admission date or the official commencement date?",
        "Can candidates joining in later counselling rounds get an extension in their MD/MS course duration?",
      ],
    },
    {
      id: "duration-dissertation",
      label: "H. Duration of Course & Dissertation",
      questions: [
        "What is the duration of MD, MS, and PG Diploma courses in Telangana?",
        "Can candidates with a PG Diploma complete an MD/MS in a shorter duration?",
        "When must MD/MS candidates register and submit their dissertation to the University?",
        "What happens if you fail to submit your dissertation within the prescribed timeline?",
        "Are conference presentations and research publications mandatory to appear for the Telangana MD/MS final examination?",
        "What academic and research requirements must every MD/MS student complete before becoming eligible for the final University examination?",
      ],
    },
    {
      id: "training-principal",
      label: "I. Period of Training & Powers of the Principal",
      questions: [
        "What is the maximum time allowed to complete an MD/MS or PG Diploma after finishing the course?",
        "What happens if you fail to clear your Telangana MD/MS final examination within the prescribed time limit?",
        "Can your MD/MS admission be cancelled after joining the course? If yes, under what circumstances?",
        "What are the consequences of submitting incorrect information or false documents during the admission process?",
        "Does the Principal have the authority to cancel an MD/MS admission, and can that decision be challenged?",
        "What is the official appeal process if your Telangana MD/MS admission is cancelled by the Principal?",
      ],
    },
  ],
  "andhra-pradesh": [
    {
      id: "regulations",
      label: "A. Regulations",
      questions: [
        "How are MD/MS seats divided between AIQ and Andhra Pradesh State Quota in Government Medical Colleges for 2025–26?",
        "What percentage of MD/MS seats are available under Competent Authority Quota in Andhra Pradesh Private Medical Colleges?",
        "Can non-local candidates understand their eligibility for Andhra Pradesh State Quota MD/MS admissions?",
        "What is the difference between Competent Authority Quota and Management Quota seats in Andhra Pradesh PG Medical Admissions?",
        "How does the Andhra Pradesh MD/MS 2025–26 seat matrix work, and how many seats are actually available under State Quota?",
        "Are there opportunities in Andhra Pradesh MD/MS admissions through Competent Authority Quota apart from All India Quota seats?",
      ],
    },
    {
      id: "local-reservation",
      label: "B. Local Candidates reservation",
      questions: [
        "Are non-local candidates eligible for Andhra Pradesh PG Medical (MD/MS) State Quota seats?",
        "How does the 85% Local Candidate reservation rule impact MD/MS admissions in Andhra Pradesh?",
        "Who qualifies as a Local Candidate for Andhra Pradesh NEET PG counselling 2025–26?",
        "Can Andhra Pradesh domicile non-local candidates apply for Unreserved (APUR) seats in MD/MS admissions?",
        "What opportunities are available for non-local doctors in Andhra Pradesh PG Medical counselling?",
        "How does the Andhra Pradesh Local and Non-Local candidate rule affect your chances of getting an MD/MS seat?",
      ],
    },
    {
      id: "institution-updates",
      label: "C. State Wise institutions updates",
      questions: [
        "How does Siddhartha Medical College’s State-wide Institution status impact MD/MS seat eligibility in Andhra Pradesh?",
        "Who qualifies as a Local Candidate for Andhra Pradesh NEET PG counselling, and how is local status determined?",
        "What are the eligibility rules for Andhra Pradesh Local Areas (Andhra University Region & Sri Venkateswara University Region) in MD/MS admissions?",
        "How is the 85% Local Seat reservation and 15% Unreserved Seat eligibility structured for Andhra Pradesh PG Medical admissions?",
        "Can candidates from outside Andhra Pradesh become eligible for the 15% Unreserved seats in AP MD/MS counselling?",
        "What documents and criteria determine your Local or Non-Local status for Andhra Pradesh NEET PG admission?",
      ],
    },
    {
      id: "in-service",
      label: "D. In-Service Quota rules",
      questions: [
        "Who is eligible for In-Service Quota seats in Andhra Pradesh MD/MS admissions 2025–26?",
        "How many MD/MS seats are reserved for Government In-Service candidates under Andhra Pradesh State Quota?",
        "What are the minimum service requirements for Tribal, Rural, and Government service candidates to claim In-Service Quota?",
        "Can Government doctors pursuing MD/MS through In-Service Quota understand the bond conditions and service obligations?",
        "What are the age limits, eligibility criteria, and important deadlines for Andhra Pradesh In-Service PG Medical admissions?",
        "What happens if an In-Service candidate fails to complete the mandatory Government service bond after MD/MS admission?",
      ],
    },
    {
      id: "non-service",
      label: "E. Non-Service Quota, Reservation & Category Eligibility",
      questions: [
        "What are the bond obligations and penalty rules for Non-Service candidates after completing MD/MS in Andhra Pradesh?",
        "How are SC, ST, and BC category reservations distributed in Andhra Pradesh PG Medical admissions 2025–26?",
        "Are caste certificates from other states accepted for Andhra Pradesh MD/MS reserved category seats?",
        "What documents are required to claim SC/ST/BC/Minority reservation benefits in Andhra Pradesh NEET PG counselling?",
        "How does Horizontal Reservation work for Women and PwBD candidates in Andhra Pradesh MD/MS admissions?",
        "Who is eligible for PwBD reservation in Andhra Pradesh PG Medical counselling, and what certificate requirements must be fulfilled?",
      ],
    },
    {
      id: "fee-structure",
      label: "F. Fee Structure, Merit List & Seat Allotment",
      questions: [
        "What is the complete fee structure for MD/MS admissions in Andhra Pradesh Private Medical Colleges for 2025–26?",
        "How much is the University Fee for Andhra Pradesh NEET PG 2025–26 admissions, and is it refundable?",
        "What are the previous year tuition fee details for Clinical, Para-Clinical, and Pre-Clinical MD/MS courses in Andhra Pradesh?",
        "How is the Andhra Pradesh NEET PG 2025 merit list prepared, and who will be eligible for web options?",
        "What is the seat allotment process for MD/MS admissions through Andhra Pradesh online counselling?",
        "How can doctors understand their chances of getting an MD/MS seat based on NEET PG rank, eligibility, and seat matrix?",
      ],
    },
    {
      id: "admission-rules",
      label: "G. Admission Rules, Bond Conditions & Security Deposit",
      questions: [
        "What are the reporting deadlines and admission formalities after getting an Andhra Pradesh MD/MS seat?",
        "What bond conditions must candidates follow after joining PG Medical courses in Andhra Pradesh?",
        "What is the penalty for discontinuing an MD/MS course after admission in Andhra Pradesh counselling?",
        "How does the ₹50,000 refundable security deposit work in Andhra Pradesh NEET PG Mop-Up Round?",
        "Will you lose your security deposit or counselling eligibility if you fail to join an allotted MD/MS seat in Andhra Pradesh?",
        "What mistakes can lead to seat cancellation or disqualification during Andhra Pradesh PG Medical admission?",
      ],
    },
    {
      id: "course-regulations",
      label: "H. Course Regulations, Break of Study & Academic Rules",
      questions: [
        "Can MD/MS students take a break from their PG course in Andhra Pradesh, and what are the re-admission rules?",
        "What is the maximum duration allowed to complete an MD/MS course after admission in Andhra Pradesh?",
        "How many times can a PG Medical student apply for a Break of Study during the course period?",
        "What happens if a candidate fails to complete the MD/MS course within the permitted duration?",
        "Are Andhra Pradesh PG Medical students allowed to do private practice or part-time work during their course?",
        "What important college and university regulations should MD/MS students follow after admission?",
      ],
    },
    {
      id: "course-duration",
      label: "I. Course Duration, Dissertation, Admission Closure & Transfer Rules",
      questions: [
        "What is the duration of MD/MS and PG Diploma courses under Andhra Pradesh NEET PG 2025–26 regulations?",
        "What happens to vacant PG Medical seats after the official closure of admissions in Andhra Pradesh counselling?",
        "What are the dissertation submission deadlines and research requirements for Andhra Pradesh MD/MS students?",
        "Can failure to complete dissertation requirements affect the completion timeline of your MD/MS course?",
        "Are MD/MS students allowed to transfer or migrate between medical colleges or courses after admission in Andhra Pradesh?",
        "What academic requirements must PG Medical students fulfil before appearing for their final MD/MS examination?",
      ],
    },
    {
      id: "counselling-process",
      label: "J. Counselling Process, Rounds, Seat Allotment & Rules",
      questions: [
        "How many rounds of counselling are conducted for Andhra Pradesh MD/MS admissions 2025–26, and what are the eligibility rules for each round?",
        "What are the important differences between Phase-I, Phase-II, Phase-III (Mop-Up), and Stray Vacancy counselling in Andhra Pradesh PG Medical admissions?",
        "How should candidates prepare their web options to maximize their chances of getting the desired MD/MS seat in Andhra Pradesh?",
        "Can candidates upgrade their allotted seat after joining in Phase-I or Phase-II counselling, and what are the conditions for upgradation?",
        "What happens if a candidate does not join an allotted seat or exits after seat allotment during Andhra Pradesh NEET PG counselling?",
        "Who is eligible to participate in Phase-III (Mop-Up) counselling, and how does the ₹50,000 security deposit rule work?",
        "Can a candidate participate in Management Quota counselling after getting a seat in Andhra Pradesh Competent Authority Quota Phase-III?",
        "What are the common mistakes that can lead to loss of seat, forfeiture of security deposit, or counselling debarment in Andhra Pradesh PG admissions?",
        "Who can participate in the Stray Vacancy Round of Andhra Pradesh NEET PG counselling, and who will be excluded?",
        "How can doctors understand their counselling strategy across AIQ, State Quota, Competent Authority Quota, and Management Quota rounds?",
      ],
    },
  ],
  karnataka: [
    {
      id: "preamble",
      label: "A. Preamble and Disclaimer",
      questions: [
        "Can non-Karnataka doctors apply for MD/MS admission in Karnataka through KEA counselling?",
        "What are the eligibility criteria for NEET PG qualified candidates to get MD/MS seats in Karnataka?",
        "Are SC/ST/OBC reservations available for non-Karnataka candidates in Karnataka PG Medical admissions?",
        "What are the different categories of MD/MS seats available in Karnataka private medical colleges?",
        "How does the Karnataka KEA counselling process work for Government, Private, Minority, and Management quota PG seats?",
        "What documents and eligibility requirements should doctors complete before registering for Karnataka NEET PG counselling 2025?",
      ],
    },
    {
      id: "general-instructions",
      label: "B. General Instructions",
      questions: [
        "What is the internship completion deadline required for Karnataka NEET PG 2025 MD/MS admission?",
        "Is there any compulsory rural service bond after completing MD/MS admission in Karnataka?",
        "Are NRI, Management, and Private Quota PG students also required to complete compulsory government service in Karnataka?",
        "Can doctors who have already completed a PG degree apply for another MD/MS course in Karnataka?",
        "What are the eligibility requirements for Foreign Medical Graduates (FMGs) applying for MD/MS admission in Karnataka?",
        "How can doctors safely complete Karnataka PG counselling without falling for fake seat guarantees or middlemen scams?",
      ],
    },
    {
      id: "notice",
      label: "C. Notice and instructions",
      questions: [
        "How can doctors get authentic updates and notifications for Karnataka NEET PG counselling 2025?",
        "How can candidates identify and avoid fake promises or guaranteed PG seat claims during Karnataka counselling?",
        "What are the important precautions doctors should take while filling the Karnataka NEET PG online application form?",
        "Can candidates modify their details after submitting the Karnataka NEET PG application form?",
        "What happens if incorrect or false information is entered during Karnataka PG counselling registration?",
        "Why is it important to preserve the Karnataka NEET PG application form throughout the counselling process?",
      ],
    },
    {
      id: "registration",
      label: "D. Registration Guide",
      questions: [
        "Who is eligible to register for Karnataka NEET PG 2025 counselling and what are the qualifying requirements?",
        "What is the step-by-step process to complete Karnataka NEET PG online registration successfully?",
        "What are the Karnataka NEET PG counselling registration fees for General, Reserved, Non-Karnataka, and NRI candidates?",
        "Can doctors edit or change details after submitting the Karnataka NEET PG application form?",
        "What documents and details are required while filling the Karnataka PG counselling application form?",
        "Why is it important to use your own mobile number and email ID during Karnataka NEET PG registration?",
      ],
    },
    {
      id: "classification",
      label: "E. Classification of Seats",
      questions: [
        "What are the different categories of Karnataka NEET PG seats (Government, Private, NRI, and Others)?",
        "Who is eligible for Government Quota (G) MD/MS seats in Karnataka private and government medical colleges?",
        "What are the eligibility criteria and opportunities available under Private Quota (P) PG medical seats in Karnataka?",
        "Can non-Karnataka doctors apply for Open (OPN) category MD/MS seats in Karnataka private medical colleges?",
        "Who can claim NRI Quota seats for MD/MS admission in Karnataka and what are the requirements?",
        "What are the Other Quota (Q) seats in Karnataka NEET PG counselling and who can apply for them?",
      ],
    },
    {
      id: "seat-eligibility",
      label: "F. Eligibility for Different types of seats",
      questions: [
        "Who is eligible for Government Quota (G) MD/MS seats in Karnataka NEET PG counselling?",
        "Can non-Karnataka doctors apply for Private, Open (OPN), NRI, and Other quota PG seats in Karnataka?",
        "What are the eligibility criteria for NRI/NRI Ward/OCI/PIO candidates seeking MD/MS admission in Karnataka?",
        "Are Christian, Muslim, Tamil, Telugu, Tulu, and Kodava minority candidates eligible for Karnataka PG Medical minority seats?",
        "What documents are required to prove eligibility for Karnataka NEET PG seat categories and minority/NRI quotas?",
        "Can doctors who completed MBBS outside Karnataka apply for MD/MS admission through Karnataka KEA counselling?",
      ],
    },
    {
      id: "in-service",
      label: "G. Instructions for In-service candidates",
      questions: [
        "Who are eligible candidates for In-Service Quota in Karnataka NEET PG counselling?",
        "What are the eligibility conditions and rules applicable for In-Service doctors applying for MD/MS admission in Karnataka?",
        "Are there any subject restrictions for In-Service candidates during Karnataka PG Medical counselling?",
        "Which documents are required to claim In-Service candidate eligibility in Karnataka NEET PG counselling?",
        "How does Karnataka KEA verify the certificates and eligibility of In-Service candidates?",
        "Can an In-Service candidate’s application or admission be cancelled if eligibility conditions are not fulfilled?",
      ],
    },
    {
      id: "minority-nri",
      label: "H. Minority, NRI & OCI/PIO candidates",
      questions: [
        "Who is eligible for Religious Minority Quota (Christian/Muslim) seats in Karnataka NEET PG counselling?",
        "Can non-Karnataka Christian and Muslim minority candidates apply for Karnataka PG Medical minority seats?",
        "What are the eligibility criteria for Linguistic Minority (Tamil, Telugu, Tulu, and Kodava) PG seats in Karnataka?",
        "Who can claim NRI Ward status for Karnataka MD/MS admission and what documents are required?",
        "What documents are required for OCI/PIO candidates applying for Karnataka NEET PG counselling?",
        "Can Foreign Nationals apply for MD/MS admission in Karnataka and what are the required eligibility documents?",
      ],
    },
    {
      id: "fee-exemption",
      label: "I. Fee Exemption / Pay details for SC / ST Karnataka candidates",
      questions: [
        "Who is eligible for fee exemption in Karnataka NEET PG counselling under SC/ST categories?",
        "What are the fee payment rules for SC/ST candidates based on annual family income?",
        "Are Category-1 candidates eligible for tuition fee exemption in Karnataka PG Medical admissions?",
        "Do OBC candidates get fee reimbursement benefits after Karnataka NEET PG admission?",
        "Are In-Service candidates eligible for fee exemption or reimbursement during Karnataka MD/MS admission?",
        "What financial requirements are applicable for NRI and Other Quota candidates during Karnataka PG admission?",
      ],
    },
    {
      id: "admission-procedure",
      label: "J. Admission Procedure",
      questions: [
        "What happens if a doctor fails to join an allotted Karnataka NEET PG seat within the given deadline?",
        "What are the cancellation charges and penalties for surrendering a Karnataka MD/MS seat after allotment?",
        "Can a candidate participate in further counselling rounds after cancelling a Karnataka PG seat?",
        "What bonds and service commitments are applicable for doctors taking Government Quota PG seats in Karnataka?",
        "What penalties apply if a candidate leaves the MD/MS course after admission?",
        "Are In-Service candidates subject to additional service bonds and recovery rules after completing or leaving the PG course?",
      ],
    },
  ],
  kerala: [
    {
      id: "intro",
      label: "A. Introductions, Duration, Fees",
      questions: [
        "Who is eligible to apply for Kerala MD/MS State Quota counselling through NEET PG 2025?",
        "Can non-Kerala doctors apply for MD/MS seats in Kerala, and under which quota?",
        "How are Government, Management, Minority and NRI MD/MS seats allotted in Kerala?",
        "What is the official fee structure for Government MD/MS colleges, and how do Self-Financing college fees differ?",
        "Which candidates are eligible for fee exemption or fee concession in Kerala PG Medical admissions?",
        "What are the important admission rules, counselling procedures and deadlines every NEET PG aspirant should know before choosing Kerala?",
      ],
    },
    {
      id: "eligibility",
      label: "B. Eligibility and Qualifying Criteria",
      questions: [
        "Who is eligible to apply for Kerala MD/MS 2025 counselling under the State Quota?",
        "Can non-Kerala doctors apply for MD/MS admissions in Kerala? What are the eligibility rules?",
        "Are OCI cardholders eligible for Kerala PG Medical admissions, and what quotas can they apply under?",
        "What are the internship, Medical Council registration and MBBS qualification requirements for Kerala MD/MS admissions?",
        "Is there any upper age limit for Kerala NEET PG counselling? Which candidates are affected?",
        "What is the minimum NEET PG 2025 qualifying percentile required for different categories in Kerala MD/MS admissions?",
      ],
    },
    {
      id: "seat-distribution",
      label: "C. Distribution & Reservation of Seats",
      questions: [
        "How are MD/MS seats distributed across Government, Self-Financing, Management, NRI and Reservation Quotas in Kerala?",
        "What reservation benefits are available for NEET PG candidates under the Kerala State Quota?",
        "How does Kerala allocate seats for EWS, SEBC, SC/ST and PwD candidates in MD/MS admissions?",
        "Who is eligible to apply under the Kerala Service Quota, and what are its benefits?",
        "Can service doctors receive additional weightage in Kerala NEET PG counselling? How is it calculated?",
        "What are the key rules, eligibility criteria and service obligations for Kerala Service Quota candidates?",
      ],
    },
    {
      id: "selection",
      label: "D. Method of Examination and mode of selection",
      questions: [
        "Is NEET PG 2025 mandatory for admission to MD/MS courses in Kerala?",
        "How is the Kerala MD/MS State Rank List prepared after the NEET PG results?",
        "Who prepares and publishes the official Kerala NEET PG Rank List and Category List?",
        "Which quotas are filled through the Kerala CEE rank list in MD/MS admissions?",
        "Can candidates secure Government, Management, Minority and NRI seats through a single Kerala counselling process?",
        "What factors determine your selection for Kerala MD/MS counselling apart from your NEET PG rank?",
      ],
    },
    {
      id: "bond",
      label: "E. Execution of Bond & Liquidated Damages",
      questions: [
        "Is a compulsory service bond mandatory for MD/MS admission in Kerala?",
        "How long is the compulsory Government service after completing MD/MS in Kerala?",
        "What happens if you discontinue your MD/MS course or violate the bond conditions?",
        "When will your original certificates be released after Kerala PG Medical admission?",
        "Can you join a Super Speciality (DM/MCh) course before completing your bonded service?",
        "What are the bond obligations and penalties for Service Quota doctors in Kerala MD/MS admissions?",
      ],
    },
    {
      id: "transfer",
      label: "F. Transfer, Duration and Joining of the candidate",
      questions: [
        "Can you transfer your MD/MS seat to another medical college after admission in Kerala?",
        "Is mutual transfer between medical colleges allowed during Kerala PG Medical admissions?",
        "What is the official duration of the MD/MS course in Kerala, and who is eligible for a reduced course duration?",
        "How is the official date of joining calculated for Kerala MD/MS courses?",
        "What is the minimum attendance required to appear for the Kerala MD/MS University examinations?",
        "What happens if your attendance or leave falls short of the mandatory requirements during the MD/MS course?",
      ],
    },
    {
      id: "oec",
      label: "G. Other Eligible Communities",
      questions: [
        "Do you belong to an OEC community? Find out if you're eligible for fee concessions in Kerala MD/MS admissions.",
        "Which communities are included under the OEC category for Kerala NEET PG counselling?",
        "Can OEC candidates receive fee concessions even if they are not eligible for reservation?",
        "What certificates are required to claim OEC benefits during Kerala MD/MS admissions?",
        "Are converted Scheduled Caste communities eligible for OEC benefits in Kerala PG Medical counselling?",
        "How can you verify whether your community qualifies for OEC fee concessions before counselling?",
      ],
    },
    {
      id: "disability",
      label: "H. Disability updates",
      questions: [
        "Are students with disabilities eligible for MBBS admission under the PwD Quota in Kerala?",
        "What percentage of disability is required to claim PwD reservation for MBBS admission?",
        "Can candidates with locomotor, visual, hearing, or speech disabilities pursue MBBS courses?",
        "Which disabilities are considered eligible and not eligible for medical admission as per MCI/NMC guidelines?",
        "Can students with learning disabilities like Dyslexia, Dyscalculia, or Autism apply for MBBS admission?",
        "How is medical fitness and eligibility assessed for PwD candidates during Kerala MBBS counselling?",
      ],
    },
  ],
  "tamil-nadu": [
    {
      id: "important",
      label: "A. Important Information",
      questions: [
        "How can I apply for Tamil Nadu MD/MS Management Quota & NRI Quota seats for the 2025-26 session?",
        "What are the important online counselling rules and updates every PG medical aspirant must know before applying in Tamil Nadu?",
        "Which documents are mandatory to upload while applying for Tamil Nadu PG Medical Admission 2025?",
        "Can I resign from an allotted seat in Tamil Nadu PG counselling? What are the online resignation rules?",
        "Who is eligible for Tamil Nadu Self-Financing Medical College Management Quota PG seats under NEET PG 2025?",
        "What mistakes should candidates avoid while filling the Tamil Nadu MD/MS counselling application form?",
      ],
    },
    {
      id: "fees",
      label: "B. Application Fee, Registration Fee & Security Deposit",
      questions: [
        "What is the total application and counselling registration fee for Tamil Nadu MD/MS Management Quota Admission 2025?",
        "Is the Tamil Nadu PG Medical application fee refundable if a candidate does not get a seat?",
        "How much security deposit is required for Tamil Nadu MD/MS Management Quota counselling?",
        "When will the security deposit be refunded if a candidate does not get any PG medical seat during counselling?",
        "In which situations can a candidate lose the security deposit amount during Tamil Nadu PG counselling?",
        "What are the important financial rules every doctor should know before participating in Tamil Nadu MD/MS counselling?",
      ],
    },
    {
      id: "general-instructions",
      label: "C. General Instructions",
      questions: [
        "How can I apply for Tamil Nadu MD/MS Management Quota & NRI Quota Admission 2025 through the official counselling portal?",
        "What is the application cum processing fee for Tamil Nadu PG Medical Admission, and how can I make the payment?",
        "Which online payment methods are accepted for Tamil Nadu MD/MS counselling registration?",
        "Is successful deduction of the application fee from my bank account enough to confirm my Tamil Nadu PG application?",
        "What precautions should candidates take to avoid payment failures or last-minute issues during Tamil Nadu PG counselling registration?",
        "What is the last date to submit the Tamil Nadu MD/MS Management Quota application form, and can late applications be accepted?",
      ],
    },
    {
      id: "eligibility",
      label: "D. Management Quota & NRI Quota Eligibility Criteria",
      questions: [
        "Who is eligible to apply for Tamil Nadu MD/MS Management Quota and NRI Quota seats in Self-Financing Medical Colleges?",
        "What are the NRI Quota eligibility rules and who can sponsor a candidate for Tamil Nadu PG Medical admission?",
        "Can NRI relatives like grandparents, uncles, aunts, or cousins sponsor a candidate for Tamil Nadu MD/MS NRI Quota seats?",
        "What documents are required to prove NRI status and relationship for Tamil Nadu PG Medical NRI Quota admission?",
        "What is the NEET PG 2025 qualifying criteria and minimum percentile required for Tamil Nadu MD/MS admission?",
        "What are the MBBS qualification, internship completion, registration, and eligibility requirements for Tamil Nadu PG Medical counselling 2025?",
      ],
    },
    {
      id: "non-eligibility",
      label: "E. Non-Eligibility Criteria",
      questions: [
        "Who are not eligible to apply for Tamil Nadu MD/MS Admission 2025 under Management Quota?",
        "Can a candidate apply for Tamil Nadu PG Medical counselling if they have already joined and discontinued a previous PG course?",
        "What are the consequences of discontinuing an allotted Tamil Nadu MD/MS seat after the specified counselling deadline?",
        "Are candidates currently pursuing MD/MS, DNB, Diploma, or equivalent PG courses eligible to apply for Tamil Nadu PG Admission 2025?",
        "Can a doctor who has already completed a PG Degree or Diploma apply for another PG Medical course in Tamil Nadu?",
        "What happens if a candidate hides or provides incorrect information regarding eligibility during Tamil Nadu PG counselling?",
      ],
    },
    {
      id: "application-procedure",
      label: "F. Application Procedure, Document Upload & NRI Documentation Requirements",
      questions: [
        "How do I correctly apply online for Tamil Nadu MD/MS Management Quota & NRI Quota admission 2025?",
        "What are the important mistakes candidates should avoid while filling the Tamil Nadu PG Medical online application form?",
        "Which documents are mandatory to upload for Tamil Nadu MD/MS counselling registration?",
        "What documents are required for NRI candidates applying for Tamil Nadu PG Medical NRI Quota seats?",
        "What are the NRI certificate verification rules and consequences of submitting incorrect NRI documents?",
        "What original certificates and documents are required during the Tamil Nadu MD/MS admission and verification process?",
      ],
    },
    {
      id: "counselling",
      label: "G. Counselling Procedure, Rounds, Seat Allotment, Resignation & Discontinuation Rules",
      questions: [
        "How many rounds of counselling are conducted for Tamil Nadu MD/MS Management Quota admissions 2025?",
        "What is the complete process of online counselling and choice filling for Tamil Nadu PG Medical admission?",
        "Can I participate in Round 2 counselling if I did not register or choice lock in Round 1?",
        "What are the rules for seat upgradation and re-allotment during Tamil Nadu MD/MS Round 2 counselling?",
        "What happens if I resign from an allotted Tamil Nadu PG seat after the permitted resignation period?",
        "How much discontinuation fee is applicable if a candidate leaves an allotted MD/MS seat after joining?",
        "What are the eligibility rules for Round 3 (Mop Up) counselling in Tamil Nadu PG Medical admission?",
        "Can a candidate participate in the Stray Vacancy Round after getting or leaving a PG seat in previous counselling rounds?",
        "What are the documents required at the time of joining the allotted Tamil Nadu MD/MS seat?",
        "What mistakes should candidates avoid during Tamil Nadu PG counselling to prevent seat cancellation, fee forfeiture, or loss of further counselling opportunities?",
      ],
    },
    {
      id: "selection-process",
      label: "H. Other Instructions and Selection Process",
      questions: [
        "How does Tamil Nadu MD/MS Management Quota & NRI Quota seat allotment work?",
        "Can unfilled NRI Quota seats be converted into Management Quota seats in Tamil Nadu PG admissions?",
        "What happens if I discontinue my allotted Tamil Nadu MD/MS seat after joining?",
        "What penalties and fee forfeitures apply if a candidate leaves a PG seat after the permitted resignation period?",
        "How can I verify whether a Tamil Nadu PG medical college and course has proper NMC approval and recognition?",
        "What should I check before choosing and locking a Tamil Nadu MD/MS seat during counselling?",
      ],
    },
    {
      id: "tuition-fee",
      label: "Tuition Fee, Payment Process & Important Instructions",
      questions: [
        "What is the tuition fee structure for Tamil Nadu MD/MS Management Quota and NRI Quota seats in Self-Financing Medical Colleges?",
        "When and how should candidates pay the tuition fee after Tamil Nadu PG seat allotment?",
        "What payment methods are available for paying Tamil Nadu MD/MS admission fees online?",
        "What should candidates do to avoid payment failures or last-minute issues during fee payment?",
        "Where can candidates raise complaints regarding excess fee collection by Self-Financing Medical Colleges?",
        "What important rules should candidates know after joining a Tamil Nadu MD/MS course?",
      ],
    },
  ],
};
